"""Formatted PDF export for Luminix health reports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

try:
    from fpdf import FPDF
except ImportError:  # pragma: no cover
    FPDF = None  # type: ignore


def _safe_text(text: str, max_len: int = 500) -> str:
    cleaned = str(text).encode("latin-1", errors="replace").decode("latin-1")
    return cleaned[:max_len] if cleaned.strip() else " "


def _section_lines(report: Dict[str, Any]) -> List[str]:
    lines: List[str] = []
    nutrition = report.get("nutrition_analysis") or {}
    anthro = nutrition.get("anthropometrics") if isinstance(nutrition, dict) else {}
    if not anthro and isinstance(nutrition, dict) and "bmi" in nutrition:
        anthro = nutrition

    if anthro:
        lines.append("BODY METRICS")
        for key in ("bmi", "bmr_kcal", "tdee_kcal", "body_fat_pct"):
            if key in anthro:
                label = key.replace("_", " ").upper()
                lines.append(f"  {label}: {anthro[key]}")
        lines.append("")

    meal = report.get("meal_plan") or report.get("weekly_plan") or {}
    days = meal.get("days") if isinstance(meal, dict) else None
    if days:
        lines.append("7-DAY MEAL PLAN")
        for day in days[:7]:
            name = day.get("day", "Day")
            meals = day.get("meals") or {}
            lines.append(f"  {name}:")
            for slot, item in list(meals.items())[:4]:
                if isinstance(item, dict):
                    lines.append(f"    {slot}: {item.get('name', str(item))}")
                else:
                    lines.append(f"    {slot}: {item}")
        lines.append("")

    pose = report.get("pose_analysis") or {}
    if pose:
        lines.append("POSE ANALYSIS")
        for key in ("mean_pose_score", "posture_label", "injury_risk_proxy"):
            if key in pose:
                lines.append(f"  {key.replace('_', ' ').title()}: {pose[key]}")
        lines.append("")

    gym = report.get("gym_plan") or report.get("workout") or {}
    exercises = gym.get("exercises") if isinstance(gym, dict) else None
    if exercises:
        lines.append(f"WORKOUT - {gym.get('category', 'Daily')}")
        for ex in exercises:
            lines.append(f"  - {ex.get('name', 'Exercise')}: {ex.get('sets', '?')} sets x {ex.get('reps', '?')}")
        lines.append("")

    summary = report.get("executive_summary") or report.get("report_human") or report.get("summary")
    if summary and isinstance(summary, str):
        lines.append("SUMMARY")
        lines.append(summary[:600])
        lines.append("")

    if len(lines) <= 2:
        lines.append("Report generated by Luminix Health Platform.")

    return lines


def export_combined_pdf(report: Dict[str, Any], out_path: str | Path) -> Path:
    if FPDF is None:
        raise RuntimeError("Install fpdf2: pip install fpdf2")

    pdf = FPDF()
    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 10, "Luminix Health Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Personalized fitness, nutrition and posture insights", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_text_color(30, 30, 30)
    usable_w = pdf.epw

    for line in _section_lines(report):
        text = _safe_text(line)
        if not text.strip():
            pdf.ln(3)
            continue
        if line.endswith(":") or (line.isupper() and len(line) < 40):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.multi_cell(usable_w, 6, text)
            pdf.set_font("Helvetica", size=10)
        else:
            pdf.multi_cell(usable_w, 5, text)

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(path))
    return path
