#!/usr/bin/env python3
"""
Generator for:
- pt (Portuguese)
- it (Italian)
- fil (Filipino - Tagalog)

Outputs pure python modules into scripts/locales_data/
"""

from pathlib import Path

LOCALES_DATA_DIR = Path(__file__).resolve().parent / "locales_data"
LOCALES_DATA_DIR.mkdir(parents=True, exist_ok=True)

# 1. PORTUGUESE (pt)
PT_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "Sistema Operacional Autônomo de Saúde e Biomecânica por IA", "version": "v4.3",
        "save": "Salvar", "cancel": "Cancelar", "confirm": "Confirmar", "delete": "Excluir", "edit": "Editar",
        "continue": "Continuar", "back": "Voltar", "next": "Próximo", "start": "Iniciar", "stop": "Parar",
        "retry": "Tentar novamente", "close": "Fechar", "search": "Buscar", "loading": "Carregando...",
        "processing": "Processando...", "success": "Sucesso", "failed": "Falhou", "error": "Erro",
        "noData": "Nenhum dado disponível", "noResults": "Nenhum resultado encontrado",
        "somethingWentWrong": "Algo deu errado", "tryAgain": "Tente novamente", "yes": "Sim", "no": "Não",
        "ok": "OK", "submit": "Enviar", "reset": "Redefinir", "download": "Baixar", "upload": "Enviar arquivo",
        "share": "Compartilhar", "copyLink": "Copiar link", "copied": "Copiado!", "viewMore": "Ver mais",
        "viewLess": "Ver menos", "learnMore": "Saiba mais", "explore": "Explorar", "skipForNow": "Pular por enquanto",
        "accept": "Aceitar", "decline": "Recusar", "send": "Enviar", "transmit": "Transmitir telemetria →",
        "scrollToTop": "Voltar ao topo", "contact": "Contato", "exploreSystem": "Explorar sistema ↓",
        "exploreSanctuary": "Explorar santuário ↓", "scrollToEnter": "Role para entrar", "breadcrumbSanctuary": "Santuário",
        "breadcrumbModules": "Módulos", "skipToContent": "Pular para o conteúdo principal", "details": "Detalhes",
        "refresh": "Atualizar", "clear": "Limpar", "filter": "Filtrar", "sort": "Ordenar", "all": "Todos",
        "none": "Nenhum", "select": "Selecionar", "selected": "Selecionado", "dismiss": "Descartar",
        "searchChambersPlaceholder": "Buscar câmaras, disciplinas e sistemas... (⌘K)", "navigate": "Navegar",
        "bannerRelease": "Edição de Primavera de Quioto",
        "bannerDetails": "— Cinemática de postura por câmera a 60 FPS e contador inteligente de repetições v4.3 já disponíveis.",
        "footerTagline": "Um passeio noturno pela biomecânica de Quioto. Cipreste queimado, luz de lanternas e uma lua vermelha renderizada em WebGL.",
        "footerChapters": "Capítulos", "footerDisciplines": "Disciplinas", "footerIntelligence": "Inteligência",
        "footerSovereignty": "Soberania", "footerHeroLink": "O Limiar", "footerGateLink": "O Portal Sanmon",
        "footerPathwaysLink": "Jardins Serenos", "footerLessonsLink": "Ofício Sagrado", "footerEternityLink": "Pós-Luz",
        "footerFaqLink": "Perguntas Frequentes", "footerCreatorLink": "O Arquiteto", "footerLivePoseLink": "Postura ao Vivo 60 FPS",
        "footerGymLink": "Motor Muscular Adaptativo", "footerYogaLink": "17 Asanas de Yoga", "footerBmiLink": "Matriz Metabólica",
        "footerFoodLink": "Nutrição & Hidratação", "footerLunaLink": "Assistente IA Luna", "footerExportLink": "Exportar Dossiê Clínico PDF",
        "footerDocsLink": "Documentação FastAPI Swagger", "footerHealthLink": "Status do Firewall", "footerShareLink": "📢 Compartilhar Plataforma",
        "footerZeroLeakLink": "Privacidade Sem Vazamentos", "footerTermsLink": "Termos de Serviço",
        "footerAccessibilityLink": "Declaração de Acessibilidade", "footerCookieSettingsLink": "Preferências de Cookies",
        "footerRobotsLink": "Índice Robots", "footerCopyright": "© 2026 LUMINIX — ENGENHARIA EDITORIAL DE QUIOTO",
        "footerBuildInfo": "ÚLTIMA ATUALIZAÇÃO: 6 DE SETEMBRO DE 2026 // BUILD 4.3-PROD",
        "footerPhilosophy": "A quietude é uma disciplina • Inteligência corporal",
        "privacy": "PRIVACIDADE", "terms": "TERMOS", "accessibility": "ACESSIBILIDADE"
    },
    "auth": {
        "login": "Entrar", "register": "Registrar", "signIn": "ENTRAR", "signOut": "Sair",
        "sanctuaryMember": "Membro do Santuário", "guest": "Convidado", "user": "Usuário", "member": "Membro",
        "viewProfileTitle": "Ver perfil de usuário e biometria", "enterSanctuary": "Entrar no Santuário",
        "createAccount": "Criar Conta", "email": "E-mail", "password": "Senha",
        "confirmPassword": "Confirmar Senha", "forgotPassword": "Esqueceu a senha?",
        "resetPassword": "Redefinir Senha", "welcomeBack": "Bem-vindo de volta",
        "sessionExpired": "Sua sessão expirou. Por favor, entre novamente.",
        "invalidCredentials": "E-mail ou senha inválidos.",
        "passwordMismatch": "As senhas não coincidem.", "passwordTooShort": "A senha deve ter no mínimo 8 caracteres.",
        "emailRequired": "O e-mail é obrigatório.", "passwordRequired": "A senha é obrigatória.",
        "security": "Segurança e Criptografia", "authenticated": "Autenticado com sucesso",
        "rememberMe": "Lembrar de mim", "orContinueWith": "Ou continuar com",
        "alreadyHaveAccount": "Já tem uma conta? Entrar", "dontHaveAccount": "Não tem uma conta? Registrar",
        "termsAgreement": "Ao continuar, você concorda com nossos Termos de Serviço e Política de Privacidade.",
        "loginSuccess": "Bem-vindo ao santuário.", "registrationSuccess": "Conta criada com sucesso.",
        "logoutSuccess": "Desconectado com sucesso.", "passwordsDoNotMatch": "As senhas não coincidem",
        "fillAllFields": "Por favor, preencha todos os campos obrigatórios", "authRequired": "Autenticação necessária",
        "signingIn": "Entrando...", "creatingAccount": "Criando conta...",
        "profile": "Perfil", "profileUpdated": "Perfil atualizado com sucesso", "avatarUpdated": "Foto de perfil atualizada",
        "newHere": "Novo por aqui? Criar cofre do santuário", "logoutConfirm": "Tem certeza de que deseja sair?",
        "firewallActive": "Proteção de firewall ativa", "firewallStatus": "WAF e limite de requisições operando"
    },
    "dashboard": {
        "heroLine1": "Onde a quietude revela", "heroLine2": "o que os olhos", "heroLine3": "não podem ver.",
        "heroTitle": "Onde a quietude revela o que os olhos não podem ver.",
        "heroSub": "Entre no Luminix por seus limiares serenos: um santuário inteligente de visão computacional a 60 FPS, protocolos de força adaptativos, alinhamento de yoga e IA Luna.",
        "launchVision": "INICIAR VISÃO 60 FPS →", "startWorkout": "INICIAR TREINO →",
        "chapterZero": "CAPÍTULO 00 — O PORTAL OCULTO // SANTUÁRIO BIOMECÂNICO",
        "thresholds": "LIMIARES", "thresholdsDesc": "Rastreamento articular a 60 FPS em tempo real e biomecânica vetorial.",
        "stillGardens": "JARDINS SERENOS", "stillGardensDesc": "Rotinas de musculação adaptativas, contador automático de repetições e descanso.",
        "sacredCraft": "OFÍCIO SAGRADO", "sacredCraftDesc": "{{count}} asanas guiadas de yoga com verificação do tempo de sustentação.",
        "nightRituals": "RITUAIS NOTURNOS", "nightRitualsDesc": "Inteligência metabólica, BMR, TDEE e matrizes de macronutrientes.",
        "peekSanmonStudio": "SANMON — Estúdio de Visão 60 FPS",
        "sanmonHead": "Cipreste queimado, pedra polida, visão computacional a 60 FPS.",
        "sanmonLead": "O Luminix começa onde o corpo físico encontra a precisão algorítmica: 33 pontos esqueléticos rastreados a 60 quadros por segundo diretamente no navegador com zero latência na nuvem. A geometria vetorial mede a flexão articular, desvio da coluna e inclinação dos ombros em tempo real.",
        "sanmonBody": "Execute agachamentos, desenvolvimentos ou avanços com alertas imediatos de risco auditivos e visuais. Nada fica oculto. Cada grau cinemático é transmitido ao vivo.",
        "sanmonCta": "Cruzar o limiar (Iniciar Postura ao Vivo)",
        "statModules": "Módulos", "statFps": "FPS Visão", "statYoga": "Asanas Yoga", "statIntelligence": "Inteligência",
        "stillGardensApproach": "Aproximação", "stillGardensApproachMeta": "Divisões Musculares Adaptativas • Reps Automáticas",
        "stillGardensApproachDesc": "Máquina de estados biomecânica de 5 fases, intervalos automáticos de descanso de 60s e divisões musculares.",
        "stillGardensLanterns": "Lanternas", "stillGardensLanternsMeta": "17 Asanas Guiadas • Cronômetro de Sustentação",
        "stillGardensLanternsDesc": "Validação de postura em tempo real, destaque dos músculos-alvo e contagem regressiva de sustentação.",
        "stillGardensMoonwater": "Água da Lua", "stillGardensMoonwaterMeta": "Matriz Metabólica • Motor de Nutrição",
        "stillGardensMoonwaterDesc": "Fórmulas clínicas duplas de BMR, TDEE, proporções de macronutrientes e análise de alimentos por IA Gemini.",
        "sacredCraftHead": "Seis disciplinas. Uma inteligência de saúde conectada.",
        "sacredCraftSub": "Cada módulo funciona como uma disciplina autônoma de engenharia, unificada por telemetria biométrica contínua.",
        "craftVisionTitle": "Visão Biomecânica", "craftVisionDesc": "Rastreamento ao vivo de 33 articulações, inclinação da coluna e alertas de risco.", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "Força Adaptativa", "craftStrengthDesc": "Divisões por grupo muscular, contador automático de repetições e cronômetro.", "craftStrengthBadge": "{{count}} Divisões",
        "craftYogaTitle": "Equilíbrio em Asanas", "craftYogaDesc": "17 posturas estruturadas de yoga com validação de ângulos articulares.", "craftYogaBadge": "{{count}} Posturas",
        "craftBmiTitle": "Alquimia Metabólica", "craftBmiDesc": "Cálculos precisos Mifflin-St Jeor e Harris-Benedict BMR, TDEE e metas macro.", "craftBmiBadge": "BMR Clínico",
        "craftFoodTitle": "Sustento Diário", "craftFoodDesc": "Registro de refeições, rastreador de hidratação e análise de comida com IA Gemini.", "craftFoodBadge": "IA Gemini",
        "craftOracleTitle": "O Oráculo", "craftOracleDesc": "Coaching conversacional com Luna IA, orientações de recuperação e planos sob medida.", "craftOracleBadge": "IA 24/7",
        "oracleHead": "Pergunte a Luna sobre treinamento, biomecânica ou dieta.",
        "oracleSub": "Com tecnologia Gemini multimodelos, Luna fornece orientação personalizada, análises cinemáticas e estratégias metabólicas.",
        "oraclePrompt1Title": "Macros para Hipertrofia", "oraclePrompt1Desc": "Calcular proteínas, carboidratos e gorduras sob medida para sobrecarga progressiva.",
        "oraclePrompt2Title": "Correção de Agachamento", "oraclePrompt2Desc": "Conselhos biomecânicos para flexão de joelho e manutenção da coluna neutra.",
        "oraclePrompt3Title": "Dieta Anti-inflamatória 7 Dias", "oraclePrompt3Desc": "Alimentos ricos em nutrientes para acelerar a regeneração dos tecidos e articulações.",
        "oracleCta": "ABRIR CONVERSA COM LUNA IA →",
        "afterlightEyebrow": "Capítulo 05 — Pós-Luz // Dossiê Clínico",
        "afterlightTitle": "Pós-Luz",
        "afterlightDesc": "O portal não se fecha atrás de você. Leve sua inteligência de saúde onde for: exporte relatórios clínicos em PDF, envie dossiês por e-mail ou gere resumos em vídeo HD.",
        "afterlightCta": "Abrir Estúdio de Exportação",
        "faqEyebrow": "Capítulo 05.5 — Perguntas Frequentes", "faqTag": "質疑 // FAQS CLÍNICAS E BIOMECÂNICAS",
        "faqHead": "Precisão Biomecânica e Arquitetura do Sistema.",
        "faqSub": "Tudo sobre privacidade local sem servidores, telemetria a 60 FPS, cinemática articular e relatórios clínicos.",
        "faqQ1": "Como o Luminix mantém visão computacional a 60 FPS sem enviar vídeos para servidores?",
        "faqA1": "O Luminix executa 100% da inferência MediaPipe no seu navegador via WebAssembly (WASM) e aceleração WebGL. Nenhum pixel ou vídeo é enviado para a nuvem.",
        "faqQ2": "Qual câmera é necessária para o rastreamento biomecânico de 33 pontos?",
        "faqA2": "Qualquer webcam padrão 720p ou 1080p, câmera integrada de laptop ou câmera de celular funciona perfeitamente.",
        "faqQ3": "Como o motor de musculação detecta repetições completas?",
        "faqA3": "Utilizamos uma máquina de estados finitos (FSM) que calcula produtos escalares de vetores articulares. Repetições só contam com amplitude completa.",
        "faqQ4": "Como a Taxa Metabólica Basal (BMR) e os macronutrientes são calculados?",
        "faqA4": "Aplicamos as equações clinicamente validadas de Mifflin-St Jeor e Harris-Benedict, multiplicadas pelo fator de atividade física (PAL).",
        "faqQ5": "Os relatórios clínicos em PDF e dados são seguros?",
        "faqA5": "Sim. Os dados locais são criptografados, protegidos por Argon2, autenticação JWT e nosso firewall contra ameaças WAF.",
        "creatorEyebrow": "Capítulo 06 — O Arquiteto", "creatorTag": "創造主 // CRIADOR E SISTEMA",
        "creatorHead": "Concebido por Ram Charan Teja com visão intransigente.",
        "creatorSub": "Por trás do Luminix está a paixão por unir visão computacional de alta frequência, rigor biomecânico e uma estética cyber de Quioto.",
        "creatorRole": "Arquiteto de Sistemas de IA Full-Stack, Engenheiro de Visão Computacional. Criador exclusivo do ecossistema Luminix.",
        "creatorBio": "MediaPipe Vision • Arquitetura FastAPI • WebGL e Three.js • LLM Gemini Multimodelo • Trigonometria Cinemática",
        "creatorViewDossier": "Ver dossiê completo do criador e arsenal tecnológico", "creatorSupportSanctuary": "Apoiar o criador"
    },
    "gym": {
        "title": "Motor Muscular Adaptativo", "pageTitle": "Motor Muscular // Contador Inteligente de Repetições",
        "moduleTag": "MÓDULO 02 // PROTOCOLOS DE FORÇA", "startWorkout": "Iniciar treino",
        "pauseWorkout": "Pausar", "resumeWorkout": "Retomar", "endWorkout": "Finalizar treino",
        "reps": "Repetições", "sets": "Séries", "weight": "Carga (kg)", "restTimer": "Descanso",
        "exercise": "Exercício", "targetMuscles": "Músculos-alvo", "formScore": "Pontuação da postura",
        "repState": "Fase", "eccentric": "Excêntrica", "concentric": "Concêntrica", "lockout": "Bloqueio",
        "depth": "Profundidade", "repPace": "Cadência", "nextExercise": "Próximo exercício", "workoutSummary": "Resumo do treino",
        "totalVolume": "Volume total", "completedSets": "Séries concluídas", "averageForm": "Forma média",
        "squat": "Agachamento", "pushup": "Flexão", "bicepCurl": "Rosca Bíceps", "overheadPress": "Desenvolvimento", "lunge": "Avanço"
    },
    "luna": {
        "title": "Luna IA // Assistente Clínica", "pageTitle": "Luna IA — Diálogo Biomecânico e Metabólico",
        "moduleTag": "MÓDULO 06 // INTELIGÊNCIA AUTÔNOMA", "askLuna": "Pergunte a Luna...",
        "askPlaceholder": "Pergunte sobre ângulos articulares, reabilitação ou nutrição...",
        "send": "Enviar", "stop": "Parar", "regenerate": "Gerar novamente", "clearChat": "Limpar histórico",
        "newChat": "Nova conversa", "thinking": "Luna está analisando seus dados fisiológicos...",
        "generating": "Formulando recomendações...", "suggestedQuestions": "Perguntas sugeridas",
        "copy": "Copiar resposta", "copied": "Copiado para a área de transferência!", "error": "Erro de comunicação com Luna",
        "retry": "Tentar novamente", "disclaimer": "Luna oferece orientações biomecânicas, mas não substitui diagnósticos médicos."
    },
    "notifications": {
        "title": "Notificações", "markAllAsRead": "Marcar todas como lidas", "noNotifications": "Nenhuma nova notificação",
        "savedSuccessfully": "Salvo com sucesso", "workoutCompleted": "Treino concluído com sucesso",
        "deviceConnected": "Dispositivo biométrico conectado", "profileUpdated": "Perfil atualizado com sucesso",
        "languageChanged": "Idioma alterado com sucesso", "analysisCompleted": "Análise biomecânica concluída",
        "connectionFailed": "Falha na conexão", "formWarning": "Atenção: desvio de postura detectado",
        "repCounted": "Repetição registrada com precisão", "restFinished": "Descanso encerrado — Pronto para a série",
        "pdfGenerated": "Dossiê clínico em PDF gerado com sucesso"
    },
    "nutrition": {
        "title": "Matriz Metabólica & Nutrição", "pageTitle": "Matriz Metabólica — BMR Clínico e TDEE",
        "moduleTag": "MÓDULO 04 // INTELIGÊNCIA METABÓLICA", "bmr": "Taxa Metabólica Basal (BMR)",
        "tdee": "Gasto Energético Diário (TDEE)", "calories": "Calorias", "protein": "Proteínas",
        "carbs": "Carboidratos", "fats": "Gorduras", "waterTracker": "Rastreador de Água", "addWater": "Adicionar água (250 ml)",
        "targetWater": "Meta de hidratação", "mealLog": "Registro de Refeições", "logMeal": "Registrar refeição",
        "foodAnalysis": "Análise de Alimentos por IA", "scanFood": "Descreva ou fotografe um alimento...",
        "dietaryGoal": "Objetivo nutricional", "hypertrophy": "Hipertrofia / Ganho muscular",
        "cutting": "Definição / Déficit calórico", "maintenance": "Manutenção", "macroBreakdown": "Distribuição de macros"
    },
    "pose": {
        "title": "Motor de Postura a 60 FPS", "pageTitle": "Postura ao Vivo (60 FPS) — Cinemática Biomecânica",
        "moduleTag": "MÓDULO 01 // CINEMÁTICA BIOMECÂNICA", "poseAnalysis": "Análise de postura",
        "startAnalysis": "Iniciar análise", "stopAnalysis": "Parar análise", "cameraPermissions": "Permissão de câmera necessária",
        "cameraInstructions": "Permita o acesso à câmera para rastreamento de movimentos a 60 FPS.",
        "grantAccess": "Conceder acesso à câmera", "bodyTracking": "Rastreamento corporal", "poseDetection": "Detecção de postura",
        "jointTracking": "Rastreamento articular", "movementTracking": "Rastreamento de movimentos", "posture": "Postura",
        "form": "Técnica", "alignment": "Alinhamento", "riskDetection": "Detecção de risco", "riskLevel": "Nível de risco",
        "movementQuality": "Qualidade do movimento", "recommendations": "Recomendações", "warnings": "Alertas",
        "exerciseFeedback": "Feedback em tempo real", "analysisResults": "Resultados da análise", "confidence": "Precisão do modelo",
        "highRisk": "Risco elevado — Corrija a postura", "mediumRisk": "Risco moderado — Ajuste os ângulos",
        "lowRisk": "Forma biomecânica excelente", "safeForm": "Execução segura", "jointAngles": "Ângulos articulares",
        "toggleAngles": "Exibir ângulos", "toggleMirror": "Espelhar câmera", "sessionDuration": "Duração da sessão",
        "alertCount": "Alertas", "fps": "Quadros por segundo (FPS)", "processing": "Processando..."
    },
    "settings": {
        "title": "Configurações do Sistema", "profile": "Perfil Biométrico", "account": "Gerenciamento de Conta",
        "language": "Idioma / Language", "appearance": "Aparência", "theme": "Tema de cores",
        "darkMode": "Modo Santuário Escuro", "lightMode": "Modo Claro", "notifications": "Notificações e Alertas",
        "privacy": "Privacidade Soberana", "security": "Segurança e Chaves", "connectedDevices": "Sensores Conectados",
        "healthDevices": "Relógios e Dispositivos", "data": "Exportação de Dados", "aiSettings": "Configurações de IA",
        "logout": "Sair da conta", "deleteAccount": "Excluir conta permanentemente",
        "deleteAccountConfirm": "Tem certeza de que deseja excluir permanentemente sua conta e todos os dados biométricos locais?",
        "saveChanges": "Salvar alterações", "changesSaved": "Configurações salvas com sucesso.",
        "fullName": "Nome completo", "age": "Idade", "bodyWeight": "Peso corporal (kg)", "heightCm": "Altura (cm)",
        "gender": "Gênero", "selectGender": "Selecione o gênero", "primaryGoal": "Objetivo principal",
        "hypertrophy": "Hipertrofia muscular", "fatLoss": "Queima de gordura", "biomechanics": "Postura e mobilidade",
        "endurance": "Resistência cardiovascular", "customProfilePicture": "Foto de perfil",
        "storedSecurely": "Criptografado com segurança no cofre local do seu navegador", "selectAvatarImage": "Escolher imagem",
        "saveInitialize": "Salvar e inicializar", "personalizeSanctuary": "Personalize seu santuário",
        "sanctuaryWord": "Santuário", "biometricRegistry": "Registro Biométrico",
        "biometricDescription": "Suas informações fisiológicas calibram o rastreamento a 60 FPS e as fórmulas metabólicas."
    },
    "yoga": {
        "title": "17 Asanas Sagradas de Yoga", "pageTitle": "Yoga // Câmara de Equilíbrio Interior",
        "moduleTag": "MÓDULO 03 // EQUILÍBRIO", "pose": "Postura Asana", "breathing": "Respiração",
        "duration": "Duração", "difficulty": "Dificuldade", "instructions": "Instruções de alinhamento",
        "startSession": "Iniciar sessão", "endSession": "Encerrar sessão", "beginner": "Iniciante",
        "intermediate": "Intermediário", "advanced": "Avançado", "safetyWarnings": "Avisos articulares",
        "recommendations": "Dicas de equilíbrio", "progress": "Progresso", "holdTime": "Tempo sustentado",
        "holdDuration": "Meta de sustentação", "poseGuide": "Guia de postura", "alignmentTips": "Dicas de alinhamento",
        "benefits": "Benefícios físicos", "asanaLibrary": "Biblioteca completa de Asanas", "selectedPose": "Postura selecionada",
        "formAccuracy": "Precisão postural", "breathingPattern": "Padrão de respiração",
        "inhale": "Inspire", "exhale": "Expire", "hold": "Retenha", "relax": "Relaxe"
    }
}

# 2. ITALIAN (it)
IT_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "Sistema Operativo Autonomo di Salute e Biomeccanica AI", "version": "v4.3",
        "save": "Salva", "cancel": "Annulla", "confirm": "Conferma", "delete": "Elimina", "edit": "Modifica",
        "continue": "Continua", "back": "Indietro", "next": "Avanti", "start": "Avvia", "stop": "Arresta",
        "retry": "Riprova", "close": "Chiudi", "search": "Cerca", "loading": "Caricamento in corso...",
        "processing": "Elaborazione...", "success": "Operazione riuscita", "failed": "Operazione non riuscita", "error": "Errore",
        "noData": "Nessun dato disponibile", "noResults": "Nessun risultato trovato",
        "somethingWentWrong": "Si è verificato un errore", "tryAgain": "Riprova", "yes": "Sì", "no": "No",
        "ok": "OK", "submit": "Invia", "reset": "Reimposta", "download": "Scarica", "upload": "Carica",
        "share": "Condividi", "copyLink": "Copia link", "copied": "Copiato!", "viewMore": "Mostra altro",
        "viewLess": "Mostra meno", "learnMore": "Scopri di più", "explore": "Esplora", "skipForNow": "Salta per ora",
        "accept": "Accetta", "decline": "Rifiuta", "send": "Invia", "transmit": "Trasmetti telemetria →",
        "scrollToTop": "Torna su", "contact": "Contatti", "exploreSystem": "Esplora il sistema ↓",
        "exploreSanctuary": "Esplora il santuario ↓", "scrollToEnter": "Scorri per entrare", "breadcrumbSanctuary": "Santuario",
        "breadcrumbModules": "Moduli", "skipToContent": "Passa al contenuto principale", "details": "Dettagli",
        "refresh": "Aggiorna", "clear": "Cancella", "filter": "Filtra", "sort": "Ordina", "all": "Tutti",
        "none": "Nessuno", "select": "Seleziona", "selected": "Selezionato", "dismiss": "Ignora",
        "searchChambersPlaceholder": "Cerca camere, discipline e sistemi... (⌘K)", "navigate": "Naviga",
        "bannerRelease": "Edizione Primaverile di Kyoto",
        "bannerDetails": "— Cinematica posturale a 60 FPS e contatore intelligente di ripetizioni v4.3 attivi.",
        "footerTagline": "Una passeggiata notturna nella biomeccanica di Kyoto. Cipresso carbonizzato, luce di lanterne e luna vermiglia renderizzata in WebGL.",
        "footerChapters": "Capitoli", "footerDisciplines": "Discipline", "footerIntelligence": "Intelligenza",
        "footerSovereignty": "Sovranità", "footerHeroLink": "La Soglia", "footerGateLink": "La Porta Sanmon",
        "footerPathwaysLink": "Giardini della Quiete", "footerLessonsLink": "Arte Sacra", "footerEternityLink": "Oltre la Luce",
        "footerFaqLink": "Domande Frequenti", "footerCreatorLink": "L'Architetto", "footerLivePoseLink": "Postura dal Vivo 60 FPS",
        "footerGymLink": "Motore Muscolare Adattivo", "footerYogaLink": "17 Asana Yoga", "footerBmiLink": "Matrice Metabolica",
        "footerFoodLink": "Nutrizione e Idratazione", "footerLunaLink": "Assistente AI Luna", "footerExportLink": "Esporta Cartella Clinica PDF",
        "footerDocsLink": "Documentazione FastAPI Swagger", "footerHealthLink": "Stato del Firewall", "footerShareLink": "📢 Condividi la Piattaforma",
        "footerZeroLeakLink": "Privacy a Zero Perdite", "footerTermsLink": "Termini di Servizio",
        "footerAccessibilityLink": "Dichiarazione di Accessibilità", "footerCookieSettingsLink": "Preferenze Cookie",
        "footerRobotsLink": "Indice Robots", "footerCopyright": "© 2026 LUMINIX — KYOTO EDITORIAL ENGINEERING",
        "footerBuildInfo": "ULTIMO AGGIORNAMENTO: 6 SETTEMBRE 2026 // BUILD 4.3-PROD",
        "footerPhilosophy": "La quiete è una disciplina • Intelligenza corporea",
        "privacy": "PRIVACY", "terms": "TERMINI", "accessibility": "ACCESSIBILITÀ"
    },
    "auth": {
        "login": "Accedi", "register": "Registrati", "signIn": "ACCEDI", "signOut": "Esci",
        "sanctuaryMember": "Membro del Santuario", "guest": "Ospite", "user": "Utente", "member": "Membro",
        "viewProfileTitle": "Visualizza profilo e dati biometrici", "enterSanctuary": "Entra nel Santuario",
        "createAccount": "Crea Account", "email": "Indirizzo e-mail", "password": "Password",
        "confirmPassword": "Conferma Password", "forgotPassword": "Password dimenticata?",
        "resetPassword": "Reimposta Password", "welcomeBack": "Bentornato",
        "sessionExpired": "Sessione scaduta. Effettua nuovamente l'accesso.",
        "invalidCredentials": "E-mail o password non validi.",
        "passwordMismatch": "Le password non coincidono.", "passwordTooShort": "La password deve contenere almeno 8 caratteri.",
        "emailRequired": "L'indirizzo e-mail è obbligatorio.", "passwordRequired": "La password è obbligatoria.",
        "security": "Sicurezza e Crittografia", "authenticated": "Autenticazione riuscita",
        "rememberMe": "Ricordami", "orContinueWith": "Oppure continua con",
        "alreadyHaveAccount": "Hai già un account? Accedi", "dontHaveAccount": "Non hai un account? Registrati",
        "termsAgreement": "Continuando, accetti i nostri Termini di Servizio e l'Informativa sulla Privacy.",
        "loginSuccess": "Benvenuto nel santuario.", "registrationSuccess": "Account creato con successo.",
        "logoutSuccess": "Disconnessione completata.", "passwordsDoNotMatch": "Le password non corrispondono",
        "fillAllFields": "Compila tutti i campi obbligatori", "authRequired": "Autenticazione richiesta",
        "signingIn": "Accesso in corso...", "creatingAccount": "Creazione account in corso...",
        "profile": "Profilo", "profileUpdated": "Profilo aggiornato con successo", "avatarUpdated": "Immagine profilo aggiornata",
        "newHere": "Nuovo utente? Crea il tuo caveau", "logoutConfirm": "Sei sicuro di voler uscire?",
        "firewallActive": "Protezione firewall attiva", "firewallStatus": "WAF e limitatore di frequenza operativi"
    },
    "dashboard": {
        "heroLine1": "Dove la quiete rivela", "heroLine2": "ciò che gli occhi", "heroLine3": "non possono vedere.",
        "heroTitle": "Dove la quiete rivela ciò che gli occhi non possono vedere.",
        "heroSub": "Varcate le soglie di Luminix: un santuario intelligente per la computer vision a 60 FPS, routine di forza adattative, allineamento yoga e intelligenza artificiale Luna.",
        "launchVision": "AVVIA VISIONE 60 FPS →", "startWorkout": "INIZIA L'ALLENAMENTO →",
        "chapterZero": "CAPITOLO 00 — LA PORTA SEGRETA // SANTUARIO BIOMECCANICO",
        "thresholds": "SOGLIE", "thresholdsDesc": "Tracciamento articolare 60 FPS in tempo reale e biomeccanica vettoriale.",
        "stillGardens": "GIARDINI DELLA QUIETE", "stillGardensDesc": "Routine di forza adattative, contatore automatico di ripetizioni e tempi di riposo.",
        "sacredCraft": "ARTE SACRA", "sacredCraftDesc": "{{count}} asana yoga guidate con verifica temporizzata della tenuta.",
        "nightRituals": "RITUALI NOTTURNI", "nightRitualsDesc": "Intelligenza metabolica, BMR, TDEE e matrici nutrizionali personalizzate.",
        "peekSanmonStudio": "SANMON — Studio Visione 60 FPS",
        "sanmonHead": "Cipresso carbonizzato, pietra levigata, visione a 60 FPS in tempo reale.",
        "sanmonLead": "Luminix ha inizio nel punto di incontro tra corpo umano e rigore algoritmico: 33 punti di riferimento scheletrici tracciati a 60 fotogrammi al secondo nel browser senza latenza cloud. La geometria vettoriale misura allineamento della colonna ed escursione articolare istante per istante.",
        "sanmonBody": "Esegui squat, distensioni o affondi con riscontro acustico e visivo in tempo reale. Nessun angolo rimane nascosto. Ogni grado cinematico viene reso all'istante.",
        "sanmonCta": "Varca la soglia (Avvia Postura dal Vivo)",
        "statModules": "Moduli", "statFps": "FPS Visione", "statYoga": "Asana Yoga", "statIntelligence": "Intelligenza",
        "stillGardensApproach": "Avvicinamento", "stillGardensApproachMeta": "Split Muscolari Adattivi • Ripetizioni Automatiche",
        "stillGardensApproachDesc": "Macchina a 5 stati biomeccanici, intervalli di recupero automatici di 60s e suddivisioni muscolari mirate.",
        "stillGardensLanterns": "Lanterne", "stillGardensLanternsMeta": "17 Asana Guidate • Timer di Tenuta",
        "stillGardensLanternsDesc": "Validazione posturale immediata, evidenziazione dei muscoli target e verifica con conto alla rovescia.",
        "stillGardensMoonwater": "Acqua Lunare", "stillGardensMoonwaterMeta": "Matrice Metabolica • Motore Nutrizionale",
        "stillGardensMoonwaterDesc": "Doppia formula clinica BMR, calcolo TDEE, ripartizione macro e analisi alimentare naturale con Gemini AI.",
        "sacredCraftHead": "Sei discipline. Un'unica intelligenza per la tua salute.",
        "sacredCraftSub": "Ogni modulo opera come una disciplina ingegneristica indipendente, raccordata da telemetria biometrica unificata.",
        "craftVisionTitle": "Visione Biomeccanica", "craftVisionDesc": "Tracciamento in tempo reale di 33 articolazioni, inclinazione vertebrale e avvisi di rischio.", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "Forza Adattiva", "craftStrengthDesc": "Programmi per gruppi muscolari, conteggio automatico da telecamera e timer di recupero.", "craftStrengthBadge": "{{count}} Split",
        "craftYogaTitle": "Equilibrio nelle Asana", "craftYogaDesc": "17 asana strutturate con verifica degli angoli articolari e del bilanciamento.", "craftYogaBadge": "{{count}} Posizioni",
        "craftBmiTitle": "Alchimia Metabolica", "craftBmiDesc": "Calcolo clinico BMR con Mifflin-St Jeor e Harris-Benedict, fabbisogno TDEE e target macro.", "craftBmiBadge": "BMR Clinico",
        "craftFoodTitle": "Sostentamento Quotidiano", "craftFoodDesc": "Diario alimentare, monitoraggio dell'idratazione e riconoscimento pasti tramite Gemini AI.", "craftFoodBadge": "Gemini AI",
        "craftOracleTitle": "L'Oracolo", "craftOracleDesc": "Coaching conversazionale con Luna AI, piani di recupero e programmi su misura.", "craftOracleBadge": "AI 24/7",
        "oracleHead": "Chiedi a Luna informazioni su allenamento, postura o dieta.",
        "oracleSub": "Forte dei modelli linguistici Gemini, Luna offre consigli personalizzati, diagnosi cinematiche e strategie metaboliche.",
        "oraclePrompt1Title": "Ripartizione Macro Ipertrofia", "oraclePrompt1Desc": "Calcola gli apporti ottimali di proteine, carboidrati e lipidi per sovraccarico progressivo.",
        "oraclePrompt2Title": "Correzione Cinematica Squat", "oraclePrompt2Desc": "Consigli biomeccanici per la flessione delle ginocchia e la neutralità della schiena.",
        "oraclePrompt3Title": "Dieta di Recupero di 7 Giorni", "oraclePrompt3Desc": "Alimenti antinfiammatori per favorire il recupero muscolare e la mobilità articolare.",
        "oracleCta": "APRI LA CONVERSAZIONE CON LUNA AI →",
        "afterlightEyebrow": "Capitolo 05 — Oltre la Luce // Dossier Clinico",
        "afterlightTitle": "Oltre la Luce",
        "afterlightDesc": "Il portale non si chiude alle tue spalle. Porta sempre con te i tuoi dati sulla salute: esporta cartelle cliniche in PDF, invia dossier via email o crea video-sintesi in HD.",
        "afterlightCta": "Apri Studio di Esportazione",
        "faqEyebrow": "Capitolo 05.5 — Domande Frequenti", "faqTag": "質疑 // FAQ CLINICHE E BIOMECCANICHE",
        "faqHead": "Precisione Biomeccanica e Architettura del Sistema.",
        "faqSub": "Tutto quello che c'è da sapere sulla riservatezza locale senza cloud, telemetria a 60 FPS e report medici.",
        "faqQ1": "Come garantisce Luminix una visione a 60 FPS senza inviare i video a server esterni?",
        "faqA1": "Tutta l'elaborazione MediaPipe avviene localmente nel browser tramite WebAssembly (WASM) e accelerazione hardware WebGL. Nessun flusso video viene mai trasmesso all'esterno.",
        "faqQ2": "Quali requisiti di videocamera sono richiesti per il tracciamento a 33 punti?",
        "faqA2": "È sufficiente una comune webcam 720p o 1080p, la fotocamera integrata del laptop o quella dello smartphone.",
        "faqQ3": "In che modo il motore di allenamento riconosce le ripetizioni valide?",
        "faqA3": "Attraverso macchine a stati finiti (FSM) che calcolano il prodotto vettoriale tra gli arti. Il conteggio scatta solo al completamento dell'intero arco di movimento.",
        "faqQ4": "Come vengono calcolati metabolismo basale (BMR) e fabbisogno calorico?",
        "faqA4": "Utilizziamo le formule validate di Mifflin-St Jeor e Harris-Benedict, moltiplicate per il livello di attività fisica (PAL).",
        "faqQ5": "I report sanitari in PDF esportati sono sicuri?",
        "faqA5": "I documenti esportati seguono standard clinici protetti da crittografia Argon2, token JWT e dal nostro Web Application Firewall (WAF).",
        "creatorEyebrow": "Capitolo 06 — L'Architetto", "creatorTag": "創造主 // CREATORE E PROGETTO",
        "creatorHead": "Creato da Ram Charan Teja con visione intransigente.",
        "creatorSub": "Luminix nasce dalla volontà di unire visione artificiale ad alta frequenza nel client, rigore biomeccanico e raffinata estetica cyber di Kyoto.",
        "creatorRole": "Architetto di Sistemi AI Full-Stack, Ingegnere di Computer Vision. Unico creatore dell'ecosistema Luminix.",
        "creatorBio": "MediaPipe Vision • Architettura FastAPI • WebGL e Three.js • LLM Gemini Multi-Modello • Trigonometria Cinematica",
        "creatorViewDossier": "Visualizza il dossier completo e l'arsenale tecnologico", "creatorSupportSanctuary": "Sostieni il creatore"
    },
    "gym": {
        "title": "Motore Muscolare Adattivo", "pageTitle": "Motore Muscolare // Contatore Intelligente di Ripetizioni",
        "moduleTag": "MODULO 02 // PROTOCOLLI DI FORZA", "startWorkout": "Inizia allenamento",
        "pauseWorkout": "Pausa", "resumeWorkout": "Riprendi", "endWorkout": "Termina sessione",
        "reps": "Ripetizioni", "sets": "Serie", "weight": "Carico (kg)", "restTimer": "Recupero",
        "exercise": "Esercizio", "targetMuscles": "Muscoli target", "formScore": "Punteggio forma",
        "repState": "Fase", "eccentric": "Eccentrica", "concentric": "Concentrica", "lockout": "Estensione",
        "depth": "Profondità", "repPace": "Ritmo", "nextExercise": "Prossimo esercizio", "workoutSummary": "Riepilogo allenamento",
        "totalVolume": "Volume totale", "completedSets": "Serie completate", "averageForm": "Forma media",
        "squat": "Squat", "pushup": "Piegamenti", "bicepCurl": "Curl Bicipiti", "overheadPress": "Lento Avanti", "lunge": "Affondo"
    },
    "luna": {
        "title": "Luna AI // Assistente Clinica", "pageTitle": "Luna AI — Dialogo Biomeccanico e Metabolico",
        "moduleTag": "MODULO 06 // INTELLIGENZA AUTONOMA", "askLuna": "Chiedi a Luna...",
        "askPlaceholder": "Chiedi consiglio su angoli articolari, riabilitazione o piani nutrizionali...",
        "send": "Invia", "stop": "Ferma", "regenerate": "Rigenera", "clearChat": "Cancella cronologia",
        "newChat": "Nuova conversazione", "thinking": "Luna sta analizzando i parametri fisiologici...",
        "generating": "Formulazione delle raccomandazioni...", "suggestedQuestions": "Domande suggerite",
        "copy": "Copia risposta", "copied": "Copiato negli appunti!", "error": "Errore di connessione con Luna",
        "retry": "Riprova", "disclaimer": "Luna offre supporto biomeccanico ma non sostituisce il parere di un medico."
    },
    "notifications": {
        "title": "Notifiche", "markAllAsRead": "Segna tutte come lette", "noNotifications": "Nessuna nuova notifica",
        "savedSuccessfully": "Salvataggio completato", "workoutCompleted": "Sessione completata con successo",
        "deviceConnected": "Dispositivo biometrico connesso", "profileUpdated": "Profilo aggiornato con successo",
        "languageChanged": "Lingua modificata con successo", "analysisCompleted": "Analisi biomeccanica completata",
        "connectionFailed": "Connessione non riuscita", "formWarning": "Attenzione: rilevata alterazione posturale",
        "repCounted": "Ripetizione registrata con precisione", "restFinished": "Recupero terminato — Pronto per la serie",
        "pdfGenerated": "Dossier clinico in PDF generato con successo"
    },
    "nutrition": {
        "title": "Matrice Metabolica e Nutrizione", "pageTitle": "Matrice Metabolica — BMR e TDEE Clinico",
        "moduleTag": "MODULO 04 // INTELLIGENZA METABOLICA", "bmr": "Metabolismo Basale (BMR)",
        "tdee": "Dispendio Energetico Totale (TDEE)", "calories": "Calorie", "protein": "Proteine",
        "carbs": "Carboidrati", "fats": "Grassi", "waterTracker": "Tracciamento Idratazione", "addWater": "Aggiungi acqua (250 ml)",
        "targetWater": "Obiettivo idratazione", "mealLog": "Registro Pasti", "logMeal": "Registra pasto",
        "foodAnalysis": "Analisi Alimenti AI", "scanFood": "Descrivi o scansiona un alimento...",
        "dietaryGoal": "Obiettivo nutrizionale", "hypertrophy": "Ipertrofia / Massa muscolare",
        "cutting": "Definizione / Perdita grasso", "maintenance": "Mantenimento", "macroBreakdown": "Ripartizione macronutrienti"
    },
    "pose": {
        "title": "Motore di Postura 60 FPS", "pageTitle": "Postura dal Vivo (60 FPS) — Cinematica Biomeccanica",
        "moduleTag": "MODULO 01 // CINEMATICA BIOMECCANICA", "poseAnalysis": "Analisi postura",
        "startAnalysis": "Avvia analisi", "stopAnalysis": "Arresta analisi", "cameraPermissions": "Autorizzazione fotocamera necessaria",
        "cameraInstructions": "Consenti l'accesso alla fotocamera per il tracciamento dei movimenti a 60 FPS.",
        "grantAccess": "Concedi accesso fotocamera", "bodyTracking": "Tracciamento corpo", "poseDetection": "Riconoscimento postura",
        "jointTracking": "Tracciamento articolare", "movementTracking": "Tracciamento movimento", "posture": "Postura",
        "form": "Esecuzione", "alignment": "Allineamento", "riskDetection": "Rilevamento rischi", "riskLevel": "Livello di rischio",
        "movementQuality": "Qualità del movimento", "recommendations": "Raccomandazioni", "warnings": "Avvisi",
        "exerciseFeedback": "Feedback immediato", "analysisResults": "Risultati dell'analisi", "confidence": "Affidabilità del modello",
        "highRisk": "Rischio elevato — Correggi la postura", "mediumRisk": "Rischio moderato — Regola gli angoli",
        "lowRisk": "Biomeccanica ottimale", "safeForm": "Esecuzione corretta", "jointAngles": "Angoli articolari",
        "toggleAngles": "Mostra angoli", "toggleMirror": "Specchia visuale", "sessionDuration": "Durata sessione",
        "alertCount": "Avvisi", "fps": "Fotogrammi/s (FPS)", "processing": "Elaborazione..."
    },
    "settings": {
        "title": "Impostazioni di Sistema", "profile": "Profilo Biometrico", "account": "Gestione Account",
        "language": "Lingua / Language", "appearance": "Aspetto", "theme": "Tema colori",
        "darkMode": "Modalità Santuario Scura", "lightMode": "Modalità Chiara", "notifications": "Notifiche e Avvisi",
        "privacy": "Riservatezza Sovrana", "security": "Sicurezza e Token", "connectedDevices": "Sensori Connessi",
        "healthDevices": "Dispositivi e Tracker", "data": "Esportazione Dati", "aiSettings": "Preferenze AI",
        "logout": "Disconnetti", "deleteAccount": "Elimina account definitivamente",
        "deleteAccountConfirm": "Sei sicuro di voler eliminare definitivamente il tuo account e tutti i dati biometrici locali?",
        "saveChanges": "Salva modifiche", "changesSaved": "Impostazioni salvate con successo.",
        "fullName": "Nome completo", "age": "Età", "bodyWeight": "Peso corporeo (kg)", "heightCm": "Altezza (cm)",
        "gender": "Genere", "selectGender": "Seleziona genere", "primaryGoal": "Obiettivo principale",
        "hypertrophy": "Ipertrofia muscolare", "fatLoss": "Riduzione massa grassa", "biomechanics": "Postura e mobilità",
        "endurance": "Resistenza cardiovascolare", "customProfilePicture": "Immagine del profilo",
        "storedSecurely": "Crittografato in sicurezza nel caveau locale del browser", "selectAvatarImage": "Seleziona immagine",
        "saveInitialize": "Salva e inizializza", "personalizeSanctuary": "Personalizza il tuo santuario",
        "sanctuaryWord": "Santuario", "biometricRegistry": "Registro Biometrico",
        "biometricDescription": "I dati fisiologici calibrano il tracciamento a 60 FPS e gli algoritmi metabolici."
    },
    "yoga": {
        "title": "17 Asana Sacre dello Yoga", "pageTitle": "Yoga // Camera dell'Equilibrio e della Serenità",
        "moduleTag": "MODULO 03 // EQUILIBRIO", "pose": "Posizione Asana", "breathing": "Respirazione",
        "duration": "Durata", "difficulty": "Difficoltà", "instructions": "Istruzioni per l'allineamento",
        "startSession": "Inizia sessione", "endSession": "Termina sessione", "beginner": "Principiante",
        "intermediate": "Intermedio", "advanced": "Avanzato", "safetyWarnings": "Avvertenze articolari",
        "recommendations": "Consigli di stabilità", "progress": "Avanzamento", "holdTime": "Tempo mantenuto",
        "holdDuration": "Tenuta stabilita", "poseGuide": "Guida alla posizione", "alignmentTips": "Suggerimenti posturali",
        "benefits": "Benefici fisiologici", "asanaLibrary": "Catalogo completo Asana", "selectedPose": "Posizione selezionata",
        "formAccuracy": "Precisione posturale", "breathingPattern": "Ritmo del respiro",
        "inhale": "Inspira", "exhale": "Espira", "hold": "Trattieni", "relax": "Rilassa"
    }
}

# 3. FILIPINO / TAGALOG (fil)
FIL_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "Sistemang Awtonomo ng AI para sa Kalusugan at Biomechanics", "version": "v4.3",
        "save": "I-save", "cancel": "Kanselahin", "confirm": "Kumpirmahin", "delete": "Tanggalin", "edit": "I-edit",
        "continue": "Magpatuloy", "back": "Bumalik", "next": "Susunod", "start": "Simulan", "stop": "Itigil",
        "retry": "Subukan Muli", "close": "Isara", "search": "Maghanap", "loading": "Naglo-load...",
        "processing": "Pinoproseso...", "success": "Tagumpay", "failed": "Nabigo", "error": "Error",
        "noData": "Walang magagamit na datos", "noResults": "Walang nahanap na resulta",
        "somethingWentWrong": "May naganap na error", "tryAgain": "Subukan muli", "yes": "Oo", "no": "Hindi",
        "ok": "OK", "submit": "Isumite", "reset": "I-reset", "download": "I-download", "upload": "I-upload",
        "share": "Ibahagi", "copyLink": "Kopyahin ang Link", "copied": "Nakopya na!", "viewMore": "Tingnan ang Higit Pa",
        "viewLess": "Tingnan ang Kaunti", "learnMore": "Matuto Pa", "explore": "Galugarin", "skipForNow": "Laktawan Muna",
        "accept": "Tanggapin", "decline": "Tanggihan", "send": "Ipadala", "transmit": "Ipadala ang Telemetriya →",
        "scrollToTop": "Bumalik sa Itaas", "contact": "Makipag-ugnayan", "exploreSystem": "Tuklasin ang Sistema ↓",
        "exploreSanctuary": "Tuklasin ang Santuwaryo ↓", "scrollToEnter": "Mag-scroll para Pumasok", "breadcrumbSanctuary": "Santuwaryo",
        "breadcrumbModules": "Mga Modyul", "skipToContent": "Laktawan sa Nilalaman", "details": "Mga Detalye",
        "refresh": "I-refresh", "clear": "Linisin", "filter": "Salain", "sort": "Ayusin", "all": "Lahat",
        "none": "Wala", "select": "Pumili", "selected": "Napili", "dismiss": "Ibalewala",
        "searchChambersPlaceholder": "Maghanap ng mga silid, disiplina, at sistema... (⌘K)", "navigate": "Mag-navigate",
        "bannerRelease": "Edisyong Tagsibol ng Kyoto",
        "bannerDetails": "— 60 FPS camera kinematic pose tracking at matalinong rep counter v4.3 ay aktibo na.",
        "footerTagline": "Isang panggabing lakad sa biomechanics ng Kyoto. Sunog na sipres, liwanag ng parol, at pulang buwan sa WebGL.",
        "footerChapters": "Mga Kabanata", "footerDisciplines": "Mga Disiplina", "footerIntelligence": "Katalinuhan",
        "footerSovereignty": "Kasarinlan", "footerHeroLink": "Ang Hangganan", "footerGateLink": "Ang Pintuang Sanmon",
        "footerPathwaysLink": "Mga Payapang Hardin", "footerLessonsLink": "Banal na Sining", "footerEternityLink": "Liwanag sa Takipsilim",
        "footerFaqLink": "Mga Madalas Itanong", "footerCreatorLink": "Ang Arkitekto", "footerLivePoseLink": "60 FPS Live Pose",
        "footerGymLink": "Matalinong Gym Engine", "footerYogaLink": "17 Yoga Asana", "footerBmiLink": "Metabolic Matrix",
        "footerFoodLink": "Nutrisyon at Tubig", "footerLunaLink": "Luna AI Kasama", "footerExportLink": "I-export ang Klinikal na PDF",
        "footerDocsLink": "Dokumentasyon ng FastAPI Swagger", "footerHealthLink": "Katayuan ng Firewall", "footerShareLink": "📢 Ibahagi ang Plataporma",
        "footerZeroLeakLink": "Zero-Leak Pribasiya", "footerTermsLink": "Mga Tuntunin ng Paggamit",
        "footerAccessibilityLink": "Pahayag sa Accessibility", "footerCookieSettingsLink": "Mga Setting ng Cookie",
        "footerRobotsLink": "Index ng Robots", "footerCopyright": "© 2026 LUMINIX — KYOTO EDITORIAL ENGINEERING",
        "footerBuildInfo": "HULING NA-UPDATE: SETYEMBRE 6, 2026 // BUILD 4.3-PROD",
        "footerPhilosophy": "Ang katahimikan ay isang disiplina • Katalinuhan ng katawan",
        "privacy": "PRIBASIYA", "terms": "MGA TUNTUNIN", "accessibility": "ACCESSIBILITY"
    },
    "auth": {
        "login": "Mag-login", "register": "Magparehistro", "signIn": "MAG-SIGN IN", "signOut": "Mag-sign Out",
        "sanctuaryMember": "Miyembro ng Santuwaryo", "guest": "Bisita", "user": "Gumagamit", "member": "Kasapi",
        "viewProfileTitle": "Tingnan ang Profile at Biometrics", "enterSanctuary": "Pumasok sa Santuwaryo",
        "createAccount": "Gumawa ng Account", "email": "Email Address", "password": "Password",
        "confirmPassword": "Kumpirmahin ang Password", "forgotPassword": "Nakalimutan ang Password?",
        "resetPassword": "I-reset ang Password", "welcomeBack": "Maligayang Pagbabalik",
        "sessionExpired": "Nag-expire na ang iyong sesyon. Mangyaring mag-login muli.",
        "invalidCredentials": "Maling email o password.",
        "passwordMismatch": "Hindi magkatugma ang mga password.", "passwordTooShort": "Dapat ay may hindi bababa sa 8 letra ang password.",
        "emailRequired": "Kinakailangan ang email address.", "passwordRequired": "Kinakailangan ang password.",
        "security": "Seguridad at Encryption", "authenticated": "Matagumpay na napatunayan",
        "rememberMe": "Tandaan ako", "orContinueWith": "O magpatuloy gamit ang",
        "alreadyHaveAccount": "May account na? Mag-login", "dontHaveAccount": "Wala pang account? Magparehistro",
        "termsAgreement": "Sa pagpapatuloy, sumasang-ayon ka sa aming Mga Tuntunin ng Paggamit at Patakaran sa Pribasiya.",
        "loginSuccess": "Maligayang pagdating sa santuwaryo.", "registrationSuccess": "Matagumpay na nagawa ang account.",
        "logoutSuccess": "Matagumpay na naka-logout.", "passwordsDoNotMatch": "Hindi magkatugma ang mga password",
        "fillAllFields": "Pakisulatan ang lahat ng kinakailangang field", "authRequired": "Kinakailangan ng pagpapatunay",
        "signingIn": "Nagla-login...", "creatingAccount": "Ginagawa ang account...",
        "profile": "Profile", "profileUpdated": "Matagumpay na na-update ang profile", "avatarUpdated": "Na-update ang larawan ng profile",
        "newHere": "Bago rito? Gumawa ng vault sa santuwaryo", "logoutConfirm": "Sigurado ka bang nais mong mag-sign out?",
        "firewallActive": "Aktibo ang proteksyon ng firewall", "firewallStatus": "Gumagana ang WAF at rate-limiting"
    },
    "dashboard": {
        "heroLine1": "Kung saan inihahayag", "heroLine2": "ng katahimikan ang hindi", "heroLine3": "nakikita ng mata.",
        "heroTitle": "Kung saan inihahayag ng katahimikan ang hindi nakikita ng mata.",
        "heroSub": "Pumasok sa Luminix sa tahimik nitong mga pintuan: Isang matalinong santuwaryo ng 60 FPS computer vision, lakas ng katawan, yoga alignment, at Luna AI.",
        "launchVision": "SIMULAN ANG 60 FPS VISION →", "startWorkout": "SIMULAN ANG PAGSASANAY →",
        "chapterZero": "KABANATA 00 — ANG LIHIM NA PINTUAN // BIOMECHANICAL SANCTUARY",
        "thresholds": "MGA HANGGANAN", "thresholdsDesc": "Real-time 60 FPS joint tracking at vector biomechanics.",
        "stillGardens": "PAYAPANG HARDIN", "stillGardensDesc": "Matalinong pag-eehersisyo, awtomatikong rep counter at mga agwat ng pahinga.",
        "sacredCraft": "BANAL NA SINING", "sacredCraftDesc": "{{count}} ginabayang yoga asana na may pagsusuri sa tagal ng paghawak.",
        "nightRituals": "GABING RITWAL", "nightRitualsDesc": "Katalinuhang metaboliko, BMR, TDEE, at mga matrix ng macronutrient.",
        "peekSanmonStudio": "SANMON — 60 FPS Vision Studio",
        "sanmonHead": "Sinunog na sipres, lumang bato, 60 FPS tracking ng paningin.",
        "sanmonLead": "Nagsisimula ang Luminix kung saan nagtatagpo ang katawan at katumpakan ng algorithm: 33 skeletal landmark na sinusubaybayan sa 60 frames bawat segundo direkta sa browser nang walang pagkaantala sa cloud. Sinusukat ng vector geometry ang pagbaluktot ng kasukasuan, gulugod, at balikat sa real-time.",
        "sanmonBody": "Magsagawa ng mga squat, overhead press, o lunge na may agarang tunog at visual na babala sa panganib. Walang nakatago. Bawat kinematic degree ay ipinapakita nang live.",
        "sanmonCta": "Tumawid sa Hangganan (Buksan ang Live Pose)",
        "statModules": "Mga Modyul", "statFps": "FPS Vision", "statYoga": "Mga Asana sa Yoga", "statIntelligence": "Katalinuhan",
        "stillGardensApproach": "Paglapit", "stillGardensApproachMeta": "Adaptive Gym Splits • Auto Reps",
        "stillGardensApproachDesc": "5-phase rep state machine, awtomatikong 60 segundong pahinga, at target na mga kalamnan.",
        "stillGardensLanterns": "Mga Parol", "stillGardensLanternsMeta": "17 Gabay na Asana • Hold Timer",
        "stillGardensLanternsDesc": "Real-time na pagsusuri ng tindig, pag-highlight sa mga target na kalamnan, at countdown hold timer.",
        "stillGardensMoonwater": "Tubig ng Buwan", "stillGardensMoonwaterMeta": "Metabolic Matrix • Food Engine",
        "stillGardensMoonwaterDesc": "Klinikal na formula ng BMR, TDEE, target ratio ng macro, at pagsusuri ng pagkain gamit ang Gemini AI.",
        "sacredCraftHead": "Anim na disiplina. Isang konektadong katalinuhan sa kalusugan.",
        "sacredCraftSub": "Bawat modyul ay gumagana bilang sariling disiplina ng inhenyeriya, pinag-isa ng tuluy-tuloy na biometric telemetry.",
        "craftVisionTitle": "Biomechanical Vision", "craftVisionDesc": "Real-time na 33-kasukasuang pagsubaybay, pagkiling ng gulugod at mga babala.", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "Lakas ng Katawan", "craftStrengthDesc": "Pagsasanay sa bawat grupo ng kalamnan, awtomatikong rep counter at timer ng pahinga.", "craftStrengthBadge": "{{count}} Splits",
        "craftYogaTitle": "Balanse ng Asana", "craftYogaDesc": "17 gabay na tindig ng yoga na may pagsusuri sa anggulo ng mga kasukasuan.", "craftYogaBadge": "{{count}} Poses",
        "craftBmiTitle": "Metabolic Alchemy", "craftBmiDesc": "Tumpak na Mifflin-St Jeor at Harris-Benedict BMR, TDEE, at mga target sa macro.", "craftBmiBadge": "Klinikal na BMR",
        "craftFoodTitle": "Araw-araw na Nutrisyon", "craftFoodDesc": "Talaan ng pagkain, pagsubaybay sa pag-inom ng tubig, at pagsusuri ng pagkain sa AI.", "craftFoodBadge": "Gemini AI",
        "craftOracleTitle": "Ang Orakulo", "craftOracleDesc": "Pakikipag-usap kay Luna AI para sa pagsasanay, gabay sa pinsala, at mga plano sa fitness.", "craftOracleBadge": "24/7 AI",
        "oracleHead": "Tanungin si Luna tungkol sa pagsasanay, biomechanics, o nutrisyon.",
        "oracleSub": "Pinapagana ng Gemini AI, nagbibigay si Luna ng personal na pagsasanay, pagsusuri sa tindig, at mga estratehiya sa metabolismo.",
        "oraclePrompt1Title": "Macro Split sa Hypertrophy", "oraclePrompt1Desc": "Kalkulahin ang protina, carbohydrates, at taba para sa pagpapalaki ng kalamnan.",
        "oraclePrompt2Title": "Pagsasaayos ng Squat", "oraclePrompt2Desc": "Biomechanical na payo para sa pagbaluktot ng tuhod at pagpapanatili ng tuwid na likod.",
        "oraclePrompt3Title": "7-Araw na Pagkaing Pampalakas", "oraclePrompt3Desc": "Masustansyang plano ng pagkain upang mapabilis ang paggaling ng kalamnan at kasukasuan.",
        "oracleCta": "BUKSAN ANG PAG-UUSAP KAY LUNA AI →",
        "afterlightEyebrow": "Kabanata 05 — Liwanag sa Takipsilim // Klinikal na Dossier",
        "afterlightTitle": "Liwanag sa Takipsilim",
        "afterlightDesc": "Hindi sumasara ang pinto sa iyong likuran. Dalhin ang iyong datos sa kalusugan kahit saan: mag-export ng klinikal na ulat sa PDF o magpadala ng buod sa email.",
        "afterlightCta": "Buksan ang Export Studio",
        "faqEyebrow": "Kabanata 05.5 — Mga Madalas Itanong", "faqTag": "質疑 // KLINIKAL AT BIOMECHANICAL NA MGA TANONG",
        "faqHead": "Katumpakan sa Biomechanics at Arkitektura ng Sistema.",
        "faqSub": "Lahat ng kailangan mong malaman tungkol sa zero-server na pribasiya, 60 FPS telemetry, at pag-export ng klinikal na ulat.",
        "faqQ1": "Paano napapanatili ng Luminix ang 60 FPS vision nang hindi nagpapadala ng video sa mga server?",
        "faqA1": "Pinapatakbo ng Luminix ang 100% ng MediaPipe machine learning nang direkta sa iyong browser gamit ang WASM at WebGL hardware acceleration. Walang pixel na ipinapadala sa server.",
        "faqQ2": "Anong kamera ang kailangan para sa 33-point biomechanics?",
        "faqA2": "Kahit anong karaniwang 720p o 1080p webcam, kamera ng laptop, o kamera ng smartphone browser ay gumagana.",
        "faqQ3": "Paano nalalaman ng Adaptive Gym Engine ang bawat rep ng ehersisyo?",
        "faqA3": "Gumagamit ito ng finite state machines (FSM) na sumusukat sa vector dot-products ng mga braso at binti. Binibilang lamang ang rep kapag kumpleto ang galaw.",
        "faqQ4": "Paano kinakalkula ang Basal Metabolic Rate (BMR) at mga macro target?",
        "faqA4": "Inilalapat namin ang mga pormulang Mifflin-St Jeor at Harris-Benedict, na pinarami sa physical activity multiplier (PAL) para makuha ang TDEE.",
        "faqQ5": "Ligtas ba ang klinikal na PDF report at mga na-export na datos?",
        "faqA5": "Oo. Ang lokal na datos ay protektado ng Argon2 encryption, JWT session token, at ng aming Web Application Firewall (WAF).",
        "creatorEyebrow": "Kabanata 06 — Ang Arkitekto", "creatorTag": "創造主 // MAY-AKDA AT SISTEMA",
        "creatorHead": "Binuo ni Ram Charan Teja nang may walang-kompromisong pananaw.",
        "creatorSub": "Sa likod ng Luminix ay ang hangaring pagsamahin ang mabilis na computer vision, klinikal na biomechanics, at estetika ng Kyoto.",
        "creatorRole": "Full-Stack AI Systems Architect, Computer Vision Engineer. Nag-iisang tagabuo ng Luminix ecosystem.",
        "creatorBio": "MediaPipe Vision • FastAPI Architecture • WebGL at Three.js • Multi-Model Gemini LLM • Kinematic Trigonometry",
        "creatorViewDossier": "Tingnan ang buong dossier ng may-akda at teknolohiya", "creatorSupportSanctuary": "Suportahan ang Lumikha"
    },
    "gym": {
        "title": "Matalinong Gym Engine", "pageTitle": "Gym Engine // Awtomatikong Rep Counter",
        "moduleTag": "MODYUL 02 // MGA PROTOKOL SA LAKAS", "startWorkout": "Simulan ang ehersisyo",
        "pauseWorkout": "I-pause", "resumeWorkout": "Ipagpatuloy", "endWorkout": "Tapusin ang sesyon",
        "reps": "Mga Rep", "sets": "Mga Set", "weight": "Bigat (kg)", "restTimer": "Pahinga",
        "exercise": "Ehersisyo", "targetMuscles": "Mga target na kalamnan", "formScore": "Iskor sa ayos",
        "repState": "Yugto", "eccentric": "Pagbaba", "concentric": "Pag-angat", "lockout": "Pag-unat",
        "depth": "Lalim", "repPace": "Bilis", "nextExercise": "Susunod na ehersisyo", "workoutSummary": "Buod ng ehersisyo",
        "totalVolume": "Kabuuang timbang", "completedSets": "Natapos na mga set", "averageForm": "Karaniwang ayos",
        "squat": "Squat", "pushup": "Push-up", "bicepCurl": "Bicep Curl", "overheadPress": "Overhead Press", "lunge": "Lunge"
    },
    "luna": {
        "title": "Luna AI // Klinikal na Kasama", "pageTitle": "Luna AI — Pag-uusap sa Biomechanics at Kalusugan",
        "moduleTag": "MODYUL 06 // AWTONOMONG KATALINUHAN", "askLuna": "Magtanong kay Luna...",
        "askPlaceholder": "Magtanong tungkol sa biomechanics, anggulo ng kasukasuan, o pagkain...",
        "send": "Ipadala", "stop": "Itigil", "regenerate": "I-generate muli", "clearChat": "Burahin ang chat",
        "newChat": "Bagong usapan", "thinking": "Sinusuri ni Luna ang iyong physiological data...",
        "generating": "Inihahanda ang payo...", "suggestedQuestions": "Mungkahing Tanong",
        "copy": "Kopyahin ang sagot", "copied": "Nakopya sa clipboard!", "error": "Hindi makakonekta kay Luna",
        "retry": "Subukan muli", "disclaimer": "Nagbibigay si Luna ng gabay sa biomechanics ngunit hindi pamalit sa payo ng doktor."
    },
    "notifications": {
        "title": "Mga Abiso", "markAllAsRead": "Markahan lahat bilang nabasa", "noNotifications": "Walang bagong abiso",
        "savedSuccessfully": "Matagumpay na na-save", "workoutCompleted": "Natapos na ang ehersisyo",
        "deviceConnected": "Nakakonekta ang biometric device", "profileUpdated": "Na-update ang profile",
        "languageChanged": "Matagumpay na napalitan ang wika", "analysisCompleted": "Tapos na ang pagsusuri sa biomechanics",
        "connectionFailed": "Nabigo ang koneksyon", "formWarning": "Babala: Hindi pantay ang ayos ng katawan",
        "repCounted": "Nabilang ang rep", "restFinished": "Tapos na ang pahinga — Handa na para sa susunod na set",
        "pdfGenerated": "Nagawa na ang klinikal na PDF report"
    },
    "nutrition": {
        "title": "Metabolic Matrix at Nutrisyon", "pageTitle": "Metabolic Matrix — Klinikal na BMR at TDEE",
        "moduleTag": "MODYUL 04 // METABOLIKONG KATALINUHAN", "bmr": "Basal Metabolic Rate (BMR)",
        "tdee": "Kabuuang Paggamit ng Enerhiya (TDEE)", "calories": "Kaloriya", "protein": "Protina",
        "carbs": "Carbohydrates", "fats": "Taba", "waterTracker": "Talaan ng Tubig", "addWater": "Magdagdag ng tubig (250 ml)",
        "targetWater": "Target na tubig", "mealLog": "Talaan ng Pagkain", "logMeal": "Itala ang pagkain",
        "foodAnalysis": "Pagsusuri ng Pagkain sa AI", "scanFood": "Ilarawan o i-scan ang pagkain...",
        "dietaryGoal": "Layunin sa diyeta", "hypertrophy": "Pagpapalaki ng kalamnan",
        "cutting": "Pagbabawas ng taba", "maintenance": "Pagpapanatili ng timbang", "macroBreakdown": "Bahagi ng mga macro"
    },
    "pose": {
        "title": "60 FPS Pose Engine", "pageTitle": "Live Pose (60 FPS) — Biomechanical Kinematics",
        "moduleTag": "MODYUL 01 // BIOMECHANICAL KINEMATICS", "poseAnalysis": "Pagsusuri ng ayos ng katawan",
        "startAnalysis": "Simulan ang pagsusuri", "stopAnalysis": "Itigil ang pagsusuri", "cameraPermissions": "Kailangan ng pahintulot sa kamera",
        "cameraInstructions": "Payagan ang access sa kamera para sa 60 FPS na pagsubaybay.",
        "grantAccess": "Payagan ang kamera", "bodyTracking": "Pagsubaybay sa katawan", "poseDetection": "Pagtukoy sa tindig",
        "jointTracking": "Pagsubaybay sa kasukasuan", "movementTracking": "Pagsubaybay sa galaw", "posture": "Tindig",
        "form": "Ayos", "alignment": "Pantay na tindig", "riskDetection": "Pagtukoy sa panganib", "riskLevel": "Antas ng panganib",
        "movementQuality": "Kalidad ng galaw", "recommendations": "Mga mungkahi", "warnings": "Mga babala",
        "exerciseFeedback": "Real-time na feedback", "analysisResults": "Resulta ng pagsusuri", "confidence": "Katumpakan ng modelo",
        "highRisk": "Mataas ang panganib — Ayusin ang tindig", "mediumRisk": "Katamtamang panganib — Ayusin ang anggulo",
        "lowRisk": "Mahusay na biomechanical form", "safeForm": "Ligtas na pagsasagawa", "jointAngles": "Mga anggulo ng kasukasuan",
        "toggleAngles": "Ipakita ang mga anggulo", "toggleMirror": "I-mirror ang kamera", "sessionDuration": "Tagal ng sesyon",
        "alertCount": "Mga babala", "fps": "Frames Bawat Segundo (FPS)", "processing": "Pinoproseso..."
    },
    "settings": {
        "title": "Mga Setting ng Sistema", "profile": "Biometric Profile", "account": "Pamamahala ng Account",
        "language": "Wika / Language", "appearance": "Hitsura", "theme": "Tema ng Kulay",
        "darkMode": "Dark Sanctuary Mode", "lightMode": "Light Mode", "notifications": "Mga Abiso at Babala",
        "privacy": "Likas na Pribasiya", "security": "Seguridad at mga Token", "connectedDevices": "Mga Nakakonektang Sensor",
        "healthDevices": "Mga Health Tracker", "data": "Pag-export ng Datos", "aiSettings": "Mga Setting ng AI",
        "logout": "Mag-sign Out", "deleteAccount": "Permanenteng tanggalin ang account",
        "deleteAccountConfirm": "Sigurado ka bang nais mong tanggalin ang iyong account at lahat ng lokal na datos?",
        "saveChanges": "I-save ang mga pagbabago", "changesSaved": "Matagumpay na na-save ang mga setting.",
        "fullName": "Buong Pangalan", "age": "Edad", "bodyWeight": "Timbang (kg)", "heightCm": "Taas (cm)",
        "gender": "Kasarian", "selectGender": "Pumili ng kasarian", "primaryGoal": "Pangunahing layunin",
        "hypertrophy": "Pagpapalaki ng kalamnan", "fatLoss": "Pagbabawas ng taba", "biomechanics": "Ayos ng katawan at mobility",
        "endurance": "Cardiovascular endurance", "customProfilePicture": "Larawan ng Profile",
        "storedSecurely": "Ligtas na naka-encrypt sa lokal na browser vault", "selectAvatarImage": "Pumili ng larawan",
        "saveInitialize": "I-save at simulan", "personalizeSanctuary": "I-personalize ang iyong santuwaryo",
        "sanctuaryWord": "Santuwaryo", "biometricRegistry": "Talaan ng Biometrics",
        "biometricDescription": "Ang iyong physiological data ay nagka-calibrate sa 60 FPS tracking at metabolic formulas."
    },
    "yoga": {
        "title": "17 Banal na Yoga Asana", "pageTitle": "Yoga // Silid ng Katahimikan at Balanse",
        "moduleTag": "MODYUL 03 // BALANSE", "pose": "Tindig ng Asana", "breathing": "Paghinga",
        "duration": "Tagal", "difficulty": "Antas ng hirap", "instructions": "Mga tagubilin sa tindig",
        "startSession": "Simulan ang sesyon", "endSession": "Tapusin ang sesyon", "beginner": "Baguhan",
        "intermediate": "Katamtaman", "advanced": "Mataas na antas", "safetyWarnings": "Babala sa kasukasuan",
        "recommendations": "Mga payo sa balanse", "progress": "Pagsulong", "holdTime": "Oras ng paghawak",
        "holdDuration": "Target na oras", "poseGuide": "Gabay sa tindig", "alignmentTips": "Mga tip sa pag-align",
        "benefits": "Mga benepisyo sa katawan", "asanaLibrary": "Kumpletong Aklatan ng Asana", "selectedPose": "Napiling tindig",
        "formAccuracy": "Katumpakan ng tindig", "breathingPattern": "Huwaran ng paghinga",
        "inhale": "Huminga nang papasok", "exhale": "Huminga nang palabas", "hold": "Pigilin ang hininga", "relax": "Magpahinga"
    }
}

# Write pt.py, it.py, fil.py
with open(LOCALES_DATA_DIR / "pt.py", "w", encoding="utf-8") as f:
    f.write('"""Portuguese (pt) translation module for Luminix."""\n\nPT_TRANSLATIONS = ' + repr(PT_TRANSLATIONS) + '\n')
print(f"Generated pt.py with {sum(len(v) for v in PT_TRANSLATIONS.values())} keys")

with open(LOCALES_DATA_DIR / "it.py", "w", encoding="utf-8") as f:
    f.write('"""Italian (it) translation module for Luminix."""\n\nIT_TRANSLATIONS = ' + repr(IT_TRANSLATIONS) + '\n')
print(f"Generated it.py with {sum(len(v) for v in IT_TRANSLATIONS.values())} keys")

with open(LOCALES_DATA_DIR / "fil.py", "w", encoding="utf-8") as f:
    f.write('"""Filipino (fil) translation module for Luminix."""\n\nFIL_TRANSLATIONS = ' + repr(FIL_TRANSLATIONS) + '\n')
print(f"Generated fil.py with {sum(len(v) for v in FIL_TRANSLATIONS.values())} keys")
