#!/usr/bin/env python3
"""
Generator for:
- ja (Japanese)
- ko (Korean)

Outputs pure python modules into scripts/locales_data/
"""

from pathlib import Path

LOCALES_DATA_DIR = Path(__file__).resolve().parent / "locales_data"
LOCALES_DATA_DIR.mkdir(parents=True, exist_ok=True)

# 1. JAPANESE (ja)
JA_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "自律型AI健康・生体力学オペレーティングシステム", "version": "v4.3",
        "save": "保存", "cancel": "キャンセル", "confirm": "確認", "delete": "削除", "edit": "編集",
        "continue": "続ける", "back": "戻る", "next": "次へ", "start": "開始", "stop": "停止",
        "retry": "再試行", "close": "閉じる", "search": "検索", "loading": "読み込み中...",
        "processing": "処理中...", "success": "成功", "failed": "失敗", "error": "エラー",
        "noData": "データがありません", "noResults": "該当する結果がありません",
        "somethingWentWrong": "問題が発生しました", "tryAgain": "もう一度お試しください", "yes": "はい", "no": "いいえ",
        "ok": "OK", "submit": "送信", "reset": "リセット", "download": "ダウンロード", "upload": "アップロード",
        "share": "共有", "copyLink": "リンクをコピー", "copied": "コピー完了！", "viewMore": "さらに表示",
        "viewLess": "折りたたむ", "learnMore": "詳細を見る", "explore": "探索する", "skipForNow": "スキップ",
        "accept": "同意する", "decline": "拒否する", "send": "送信", "transmit": "テレメトリを送信 →",
        "scrollToTop": "トップへ戻る", "contact": "お問い合わせ", "exploreSystem": "システムを探索 ↓",
        "exploreSanctuary": "聖域を探索 ↓", "scrollToEnter": "スクロールして入館", "breadcrumbSanctuary": "聖域",
        "breadcrumbModules": "モジュール", "skipToContent": "メインコンテンツへスキップ", "details": "詳細",
        "refresh": "更新", "clear": "消去", "filter": "絞り込み", "sort": "並び替え", "all": "すべて",
        "none": "なし", "select": "選択", "selected": "選択済み", "dismiss": "閉じる",
        "searchChambersPlaceholder": "部屋・規律・システムを検索... (⌘K)", "navigate": "移動",
        "bannerRelease": "京都スプリングリリース",
        "bannerDetails": "— 60 FPSカメラ姿勢キネマティクス＆自動レップカウンター v4.3 が稼働開始。",
        "footerTagline": "京都の生体力学を巡る夜の散策。焦がし杉、灯籠の光、そしてWebGLで描かれる深紅の月。",
        "footerChapters": "章一覧", "footerDisciplines": "鍛錬一覧", "footerIntelligence": "知能",
        "footerSovereignty": "主権", "footerHeroLink": "敷居", "footerGateLink": "山門",
        "footerPathwaysLink": "静寂の庭", "footerLessonsLink": "手業", "footerEternityLink": "残光",
        "footerFaqLink": "質疑応答", "footerCreatorLink": "創造主", "footerLivePoseLink": "60 FPS リアルタイム姿勢",
        "footerGymLink": "適応型筋力エンジン", "footerYogaLink": "17のヨガ・アーサナ", "footerBmiLink": "代謝マトリクス",
        "footerFoodLink": "栄養・水分管理", "footerLunaLink": "AIコンパニオン Luna", "footerExportLink": "臨床カルテPDF出力",
        "footerDocsLink": "FastAPI Swagger仕様書", "footerHealthLink": "ファイアウォール稼働状態", "footerShareLink": "📢 プラットフォームを共有",
        "footerZeroLeakLink": "ゼロ漏洩プライバシー", "footerTermsLink": "利用規約",
        "footerAccessibilityLink": "アクセシビリティ方針", "footerCookieSettingsLink": "Cookie設定",
        "footerRobotsLink": "Robotsインデックス", "footerCopyright": "© 2026 LUMINIX — KYOTO EDITORIAL ENGINEERING",
        "footerBuildInfo": "最終更新: 2026年9月6日 // BUILD 4.3-PROD",
        "footerPhilosophy": "静けさは一つの技である • 身体知性",
        "privacy": "プライバシー", "terms": "利用規約", "accessibility": "アクセシビリティ"
    },
    "auth": {
        "login": "ログイン", "register": "会員登録", "signIn": "サインイン", "signOut": "サインアウト",
        "sanctuaryMember": "聖域門弟", "guest": "ゲスト", "user": "ユーザー", "member": "会員",
        "viewProfileTitle": "門弟調書および生体情報を表示", "enterSanctuary": "聖域に入門",
        "createAccount": "新規アカウント作成", "email": "メールアドレス", "password": "パスワード",
        "confirmPassword": "パスワードの再確認", "forgotPassword": "パスワードをお忘れですか？",
        "resetPassword": "パスワードを再設定", "welcomeBack": "おかえりなさいませ",
        "sessionExpired": "セッションの期限が切れました。再度ログインしてください。",
        "invalidCredentials": "メールアドレスまたはパスワードが正しくありません。",
        "passwordMismatch": "パスワードが一致しません。", "passwordTooShort": "パスワードは8文字以上である必要があります。",
        "emailRequired": "メールアドレスは必須です。", "passwordRequired": "パスワードは必須です。",
        "security": "セキュリティと暗号化", "authenticated": "認証に成功しました",
        "rememberMe": "ログイン状態を保持する", "orContinueWith": "または以下で続行",
        "alreadyHaveAccount": "既にアカウントをお持ちですか？ ログイン", "dontHaveAccount": "アカウントをお持ちでないですか？ 登録",
        "termsAgreement": "続行することで、利用規約およびプライバシーポリシーに同意したものとみなされます。",
        "loginSuccess": "聖域への入門が完了しました。", "registrationSuccess": "アカウントが正常に作成されました。",
        "logoutSuccess": "ログアウトしました。", "passwordsDoNotMatch": "パスワードが一致しません",
        "fillAllFields": "すべての必須項目を入力してください", "authRequired": "認証が必要です",
        "signingIn": "サインイン中...", "creatingAccount": "アカウント作成中...",
        "profile": "調書", "profileUpdated": "プロフィールを更新しました", "avatarUpdated": "写真を更新しました",
        "newHere": "初めての方へ：聖域の保管庫を開設", "logoutConfirm": "本当にサインアウトしますか？",
        "firewallActive": "ファイアウォール保護有効", "firewallStatus": "WAFおよびレート制限稼働中"
    },
    "dashboard": {
        "heroLine1": "静けさの中にこそ、", "heroLine2": "目に見えぬ本質が", "heroLine3": "立ち現れる。",
        "heroTitle": "静けさの中にこそ、目に見えぬ本質が立ち現れる。",
        "heroSub": "静寂の敷居を越え、Luminixへ。60 FPSコンピュータビジョン、適応型筋力トレーニング、ヨガの整軸、そして知性Lunaが調和する生体力学の聖域。",
        "launchVision": "60 FPSビジョン起動 →", "startWorkout": "鍛錬を開始する →",
        "chapterZero": "第零章 — 隠れ門 // 生体力学の聖域",
        "thresholds": "敷居", "thresholdsDesc": "実時間60 FPS骨格追跡と関節ベクトルの生体力学。",
        "stillGardens": "静寂の庭", "stillGardensDesc": "適応型筋力分割プログラム、自動レップ計測および休息周期。",
        "sacredCraft": "手業", "sacredCraftDesc": "{{count}}の選ばれしヨガ・アーサナと維持静止判定。",
        "nightRituals": "夜の儀", "nightRitualsDesc": "代謝知能、基礎代謝量(BMR)、総消費カロリー(TDEE)および三大栄養素設計。",
        "peekSanmonStudio": "山門 — 60 FPS ビジョンスタジオ",
        "sanmonHead": "焦がし杉、古き石段、毎秒60フレームの視覚追跡。",
        "sanmonLead": "肉体とアルゴリズムの精密性が交差する場所、それがLuminixの起点です。ブラウザ内でクラウド遅延なく、毎秒60フレームで33箇所の骨格座標を追跡。ベクトルの幾何学計算により関節屈曲、背骨の傾き、肩の歪みを実時間で計測します。",
        "sanmonBody": "スクワットやプレス、ランジを即時の視覚・聴覚リスク警告とともに実践。隠されたものは何一つありません。あらゆるキネマティクスの角度がそのまま描画されます。",
        "sanmonCta": "敷居を越える（リアルタイム姿勢起動）",
        "statModules": "モジュール", "statFps": "FPS ビジョン", "statYoga": "ヨガ・アーサナ", "statIntelligence": "知能",
        "stillGardensApproach": "参道", "stillGardensApproachMeta": "適応型筋力分割 • 自動レップ計測",
        "stillGardensApproachDesc": "5段階の生体力学ステートマシン、自動60秒インターバル、および筋肉部位別メニュー。",
        "stillGardensLanterns": "灯籠", "stillGardensLanternsMeta": "17の導きのアーサナ • 静止タイマー",
        "stillGardensLanternsDesc": "実時間姿勢検証、対象筋肉の視覚化、および秒読み静止ホールド測定。",
        "stillGardensMoonwater": "月影", "stillGardensMoonwaterMeta": "代謝マトリクス • 栄養知能",
        "stillGardensMoonwaterDesc": "臨床規格の二重BMR計算式、TDEE算出、PFCバランス設計、およびGemini AIによる自然言語食事診断。",
        "sacredCraftHead": "六つの鍛錬。統合された一つの健康知能。",
        "sacredCraftSub": "各モジュールは自律した工学的規律として機能し、一元化された生体テレメトリで連結されています。",
        "craftVisionTitle": "生体力学的視覚", "craftVisionDesc": "33関節のリアルタイム追跡、脊椎傾斜テレメトリ、および姿勢危険警報。", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "適応型筋力", "craftStrengthDesc": "筋群別分割鍛錬、カメラによる自動レップ計数、および休息管理。", "craftStrengthBadge": "{{count}} 分割",
        "craftYogaTitle": "アーサナの調和", "craftYogaDesc": "17の体系化されたヨガポーズ、関節角度の検証と静止判定。", "craftYogaBadge": "{{count}} 態",
        "craftBmiTitle": "代謝の錬金術", "craftBmiDesc": "臨床基準に基づくMifflin-St Jeor・Harris-Benedict式、TDEE、マクロ栄養設計。", "craftBmiBadge": "臨床BMR",
        "craftFoodTitle": "日々の養生", "craftFoodDesc": "毎日の食事記帳、水分補給記録、およびGemini AI食事分析。", "craftFoodBadge": "Gemini AI",
        "craftOracleTitle": "神託（オラクル）", "craftOracleDesc": "Luna AI対話型指導、怪我予防と回復指南、個別プログラム生成。", "craftOracleBadge": "24/7 AI",
        "oracleHead": "鍛錬、生体力学、栄養についてLunaに尋ねる。",
        "oracleSub": "マルチモデルGeminiを中核とするLunaが、対話式コーチング、キネマティクス姿勢診断、代謝戦略を授けます。",
        "oraclePrompt1Title": "筋肥大マクロ栄養素設計", "oraclePrompt1Desc": "漸進性過負荷に適したタンパク質、炭水化物、脂質の最適比率を算出する。",
        "oraclePrompt2Title": "スクワットの軌道修正", "oraclePrompt2Desc": "膝の屈曲角度の最適化と腰椎のニュートラル維持に関する生体力学的指南。",
        "oraclePrompt3Title": "7日間の回復養生食", "oraclePrompt3Desc": "組織修復と関節の柔軟性を促す抗炎症・高密度栄養メニュー。",
        "oracleCta": "LUNA AI との対話を開く →",
        "afterlightEyebrow": "第五章 — 残光 // 臨床調書と出力",
        "afterlightTitle": "残光",
        "afterlightDesc": "門はあなたの背後で閉ざされることはありません。蓄積された健康知能をどこへでも持ち出せます。PDF臨床カルテの書き出し、電子書面送付、高画質解説映像の生成が可能です。",
        "afterlightCta": "出力工房を開く",
        "faqEyebrow": "第五・五章 — 質疑応答", "faqTag": "質疑 // 臨床・生体力学の仕様",
        "faqHead": "生体力学的精密性とシステム構成。",
        "faqSub": "ゼロサーバープライバシー、60 FPSビジョンテレメトリ、関節キネマティクス、カルテ出力に関する全情報。",
        "faqQ1": "映像を外部サーバーに送信することなく、どのように60 FPSビジョンを実現していますか？",
        "faqA1": "MediaPipe推論の100%がWebAssembly (WASM)とWebGLハードウェアアクセラレーションを介し、ブラウザ内で完結して実行されます。映像データが外部へ送信されることは一切ありません。",
        "faqQ2": "33箇所の生体力学測定に必要なカメラ仕様は？",
        "faqA2": "標準的な720pまたは1080pのWebカメラ、ノートPC内蔵カメラ、スマートフォンのブラウザカメラで完全に動作します。",
        "faqQ3": "適応型筋力エンジンはどのように正確なレップ数を判別しますか？",
        "faqA3": "単純なしきい値ではなく、四肢のベクトル内積を測定する有限オートマトン（FSM）を採用しています。完全な伸展と収縮が行われた場合のみ加算されます。",
        "faqQ4": "基礎代謝量（BMR）と三大栄養素比率はどのように計算されますか？",
        "faqA4": "臨床的に検証されたMifflin-St Jeor式および改定Harris-Benedict式に身体活動レベル（PAL）を乗じてTDEEを導出します。",
        "faqQ5": "臨床PDFカルテと生体データの安全性は確保されていますか？",
        "faqA5": "出力書類は医療要約指針に準拠しています。ローカルデータはArgon2暗号化、JWT認証、および統合WAFファイアウォールにより厳格に守られています。",
        "creatorEyebrow": "第六章 — 創造主", "creatorTag": "創造主 // 開発者と手業",
        "creatorHead": "妥協なき理念に基づき Ram Charan Teja が設計。",
        "creatorSub": "Luminixの根底には、クライアント完結の超高速コンピュータビジョン、臨床生体力学、そして京都のサイバー美学を融合させるという執念が存在します。",
        "creatorRole": "フルスタックAIシステムアーキテクト、コンピュータビジョンエンジニア。Luminixの全機構を独力で構築。",
        "creatorBio": "MediaPipe Vision • FastAPI基盤 • WebGL & Three.js • マルチモデルGemini LLM • キネマティクス三角法 • 天与呪縛",
        "creatorViewDossier": "創造主調書および技術兵器録を見る", "creatorSupportSanctuary": "開発者を支援する"
    },
    "gym": {
        "title": "適応型筋力エンジン", "pageTitle": "筋力エンジン // 高精度レップカウンター",
        "moduleTag": "モジュール 02 // 筋力プロトコル", "startWorkout": "鍛錬開始",
        "pauseWorkout": "一時停止", "resumeWorkout": "再開", "endWorkout": "鍛錬終了",
        "reps": "回数", "sets": "セット", "weight": "重量 (kg)", "restTimer": "休息時間",
        "exercise": "種目", "targetMuscles": "対象筋群", "formScore": "姿勢採点",
        "repState": "動作段階", "eccentric": "降下相（エキセントリック）", "concentric": "上昇相（コンセントリック）", "lockout": "伸展完了",
        "depth": "深さ", "repPace": "ペース", "nextExercise": "次の種目", "workoutSummary": "鍛錬総括",
        "totalVolume": "総負荷量", "completedSets": "完了セット数", "averageForm": "平均姿勢点",
        "squat": "スクワット", "pushup": "腕立て伏せ", "bicepCurl": "アームカール", "overheadPress": "ショルダープレス", "lunge": "ランジ"
    },
    "luna": {
        "title": "Luna AI // 臨床指南役", "pageTitle": "Luna AI — 生体力学・代謝対話システム",
        "moduleTag": "モジュール 06 // 自律型人工知能", "askLuna": "Lunaに問う...",
        "askPlaceholder": "関節の角度、怪我の予防、食事方針などをお尋ねください...",
        "send": "送信", "stop": "中止", "regenerate": "再生成", "clearChat": "履歴を消去",
        "newChat": "新しい問答", "thinking": "Lunaが生体指標を解析中...",
        "generating": "指南文を編纂中...", "suggestedQuestions": "おすすめの問い",
        "copy": "回答を複製", "copied": "クリップボードに保存しました！", "error": "Luna AIとの接続に失敗しました",
        "retry": "再試行", "disclaimer": "Lunaは生体力学の指標を提示しますが、医師の診断に代わるものではありません。"
    },
    "notifications": {
        "title": "通知", "markAllAsRead": "すべて既読にする", "noNotifications": "新しい通知はありません",
        "savedSuccessfully": "正常に保存されました", "workoutCompleted": "鍛錬が完了しました",
        "deviceConnected": "生体測定端末が接続されました", "profileUpdated": "門弟調書が更新されました",
        "languageChanged": "言語を変更しました", "analysisCompleted": "生体力学解析が完了しました",
        "connectionFailed": "接続に失敗しました", "formWarning": "警告: 骨格の傾きが検知されました",
        "repCounted": "動作が正しく計数されました", "restFinished": "休息終了 — 次のセットへ",
        "pdfGenerated": "カルテPDFが正常に出力されました"
    },
    "nutrition": {
        "title": "代謝マトリクス・栄養知能", "pageTitle": "代謝マトリクス — 臨床BMRおよびTDEE",
        "moduleTag": "モジュール 04 // 代謝知能", "bmr": "基礎代謝量 (BMR)",
        "tdee": "総消費エネルギー量 (TDEE)", "calories": "カロリー", "protein": "タンパク質",
        "carbs": "炭水化物", "fats": "脂質", "waterTracker": "水分追跡器", "addWater": "水を追加 (250 ml)",
        "targetWater": "目標水分摂取量", "mealLog": "食事記帳", "logMeal": "食事を記録",
        "foodAnalysis": "AI食事分析", "scanFood": "食事の内容を入力または撮影...",
        "dietaryGoal": "養生方針", "hypertrophy": "筋肥大 / 筋量増加",
        "cutting": "減量 / 脂肪燃焼", "maintenance": "現状維持", "macroBreakdown": "PFCバランス構成"
    },
    "pose": {
        "title": "60 FPS 姿勢エンジン", "pageTitle": "リアルタイム姿勢判定 (60 FPS) — 生体力学キネマティクス",
        "moduleTag": "モジュール 01 // 生体力学キネマティクス", "poseAnalysis": "姿勢解析",
        "startAnalysis": "解析開始", "stopAnalysis": "解析停止", "cameraPermissions": "カメラ使用の許可が必要です",
        "cameraInstructions": "60 FPS動作追跡を行うため、カメラへのアクセスを許可してください。",
        "grantAccess": "カメラを許可する", "bodyTracking": "全身追跡", "poseDetection": "姿勢検出",
        "jointTracking": "関節追跡", "movementTracking": "動作追跡", "posture": "姿勢",
        "form": "フォーム", "alignment": "整軸", "riskDetection": "危険検知", "riskLevel": "危険度",
        "movementQuality": "動作の品位", "recommendations": "改善指南", "warnings": "警告",
        "exerciseFeedback": "即時評価", "analysisResults": "解析結果", "confidence": "モデル信頼度",
        "highRisk": "危険度高 — フォームを正してください", "mediumRisk": "注意 — 関節の角度を確認してください",
        "lowRisk": "理想的な生体力学フォーム", "safeForm": "安全な動作", "jointAngles": "関節角度",
        "toggleAngles": "角度表示の切替", "toggleMirror": "鏡像反転", "sessionDuration": "時間",
        "alertCount": "警告回数", "fps": "フレームレート (FPS)", "processing": "解析処理中..."
    },
    "settings": {
        "title": "システム設定", "profile": "生体プロファイル", "account": "アカウント管理",
        "language": "言語 / Language", "appearance": "外観", "theme": "色彩主題",
        "darkMode": "聖域暗黒調（ダーク）", "lightMode": "明朝調（ライト）", "notifications": "通知と警報",
        "privacy": "不可侵プライバシー", "security": "防壁と暗号鍵", "connectedDevices": "接続済み測定器",
        "healthDevices": "生体追跡機器", "data": "データ出力と保管庫", "aiSettings": "AI知能設定",
        "logout": "サインアウト", "deleteAccount": "アカウントの完全抹消",
        "deleteAccountConfirm": "アカウントおよび保存された全生体データを恒久的に抹消しますか？",
        "saveChanges": "変更を保存", "changesSaved": "設定が正常に保存されました。",
        "fullName": "氏名", "age": "年齢", "bodyWeight": "体重 (kg)", "heightCm": "身長 (cm)",
        "gender": "性別", "selectGender": "性別を選択", "primaryGoal": "最大の目的",
        "hypertrophy": "筋力増強・筋肥大", "fatLoss": "脂肪燃焼・体型引締", "biomechanics": "姿勢改善・機能回復",
        "endurance": "心肺持久力向上", "customProfilePicture": "人物画",
        "storedSecurely": "端末のローカル保管庫にて暗号化保護中", "selectAvatarImage": "画像を選択",
        "saveInitialize": "保存して初期化する", "personalizeSanctuary": "あなたの聖域を誂える",
        "sanctuaryWord": "聖域", "biometricRegistry": "生体原簿",
        "biometricDescription": "入力された生理学的指標が60 FPS視覚判定と代謝計算を精密に調整します。"
    },
    "yoga": {
        "title": "17の神聖なるヨガ・アーサナ", "pageTitle": "ヨガ // 心身調和の間",
        "moduleTag": "モジュール 03 // 調和", "pose": "アーサナ（姿勢）", "breathing": "調息",
        "duration": "維持時間", "difficulty": "難易度", "instructions": "整軸の心得",
        "startSession": "行法開始", "endSession": "行法終了", "beginner": "初級",
        "intermediate": "中級", "advanced": "上級", "safetyWarnings": "関節保護の注意",
        "recommendations": "調和の要訣", "progress": "修練進度", "holdTime": "現在の維持秒数",
        "holdDuration": "目標維持秒数", "poseGuide": "姿勢の規範", "alignmentTips": "骨格の揃え方",
        "benefits": "身体への恩恵", "asanaLibrary": "全アーサナ録", "selectedPose": "選択中の姿勢",
        "formAccuracy": "姿勢の正確度", "breathingPattern": "呼吸の拍子",
        "inhale": "吸気", "exhale": "呼気", "hold": "止息", "relax": "弛緩"
    }
}

# 2. KOREAN (ko)
KO_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "자율형 AI 건강 및 생체역학 운영체제", "version": "v4.3",
        "save": "저장", "cancel": "취소", "confirm": "확인", "delete": "삭제", "edit": "편집",
        "continue": "계속", "back": "뒤로", "next": "다음", "start": "시작", "stop": "중지",
        "retry": "다시 시도", "close": "닫기", "search": "검색", "loading": "로딩 중...",
        "processing": "처리 중...", "success": "성공", "failed": "실패", "error": "오류",
        "noData": "데이터가 없습니다", "noResults": "결과를 찾을 수 없습니다",
        "somethingWentWrong": "문제가 발생했습니다", "tryAgain": "다시 시도해주세요", "yes": "예", "no": "아니오",
        "ok": "확인", "submit": "제출", "reset": "초기화", "download": "다운로드", "upload": "업로드",
        "share": "공유", "copyLink": "링크 복사", "copied": "복사되었습니다!", "viewMore": "더 보기",
        "viewLess": "간략히 보기", "learnMore": "자세히 알아보기", "explore": "탐색하기", "skipForNow": "건너뛰기",
        "accept": "수락", "decline": "거절", "send": "보내기", "transmit": "원격 측정 데이터 전송 →",
        "scrollToTop": "맨 위로 이동", "contact": "문의하기", "exploreSystem": "시스템 탐색 ↓",
        "exploreSanctuary": "성역 탐색 ↓", "scrollToEnter": "스크롤하여 입장", "breadcrumbSanctuary": "성역",
        "breadcrumbModules": "모듈", "skipToContent": "본문으로 건너뛰기", "details": "상세정보",
        "refresh": "새로고침", "clear": "지우기", "filter": "필터", "sort": "정렬", "all": "전체",
        "none": "없음", "select": "선택", "selected": "선택됨", "dismiss": "닫기",
        "searchChambersPlaceholder": "수련실, 종목 및 시스템 검색... (⌘K)", "navigate": "이동",
        "bannerRelease": "교토 스프링 릴리스",
        "bannerDetails": "— 60 FPS 카메라 키네마틱 자세 추적 및 스마트 반복 횟수 측정 v4.3 적용 완료.",
        "footerTagline": "교토 생체역학의 밤길 산책. 그을린 편백, 등불의 빛, 그리고 실시간 WebGL로 렌더링된 붉은 달.",
        "footerChapters": "장 (Chapters)", "footerDisciplines": "수련 종목", "footerIntelligence": "지능",
        "footerSovereignty": "주권", "footerHeroLink": "문턱", "footerGateLink": "산문 (Sanmon)",
        "footerPathwaysLink": "고요한 정원", "footerLessonsLink": "신성한 기술", "footerEternityLink": "여광 (Afterlight)",
        "footerFaqLink": "자주 묻는 질문", "footerCreatorLink": "설계자", "footerLivePoseLink": "60 FPS 실시간 자세",
        "footerGymLink": "적응형 근력 엔진", "footerYogaLink": "17가지 요가 아사나", "footerBmiLink": "대사 매트릭스",
        "footerFoodLink": "영양 및 수분", "footerLunaLink": "Luna AI 동반자", "footerExportLink": "임상 PDF 보고서 출력",
        "footerDocsLink": "FastAPI Swagger 문서", "footerHealthLink": "방화벽 상태", "footerShareLink": "📢 플랫폼 공유하기",
        "footerZeroLeakLink": "무누출 개인정보 보호", "footerTermsLink": "이용약관",
        "footerAccessibilityLink": "접근성 선언", "footerCookieSettingsLink": "쿠키 환경설정",
        "footerRobotsLink": "Robots 색인", "footerCopyright": "© 2026 LUMINIX — KYOTO EDITORIAL ENGINEERING",
        "footerBuildInfo": "최종 업데이트: 2026년 9월 6일 // BUILD 4.3-PROD",
        "footerPhilosophy": "고요함은 하나의 규율이다 • 신체 지능",
        "privacy": "개인정보 보호", "terms": "이용약관", "accessibility": "접근성"
    },
    "auth": {
        "login": "로그인", "register": "회원가입", "signIn": "로그인", "signOut": "로그아웃",
        "sanctuaryMember": "성역 회원", "guest": "게스트", "user": "사용자", "member": "회원",
        "viewProfileTitle": "사용자 프로필 및 생체 측정 보기", "enterSanctuary": "성역 입장",
        "createAccount": "계정 만들기", "email": "이메일 주소", "password": "비밀번호",
        "confirmPassword": "비밀번호 확인", "forgotPassword": "비밀번호를 잊으셨나요?",
        "resetPassword": "비밀번호 재설정", "welcomeBack": "다시 오신 것을 환영합니다",
        "sessionExpired": "세션이 만료되었습니다. 다시 로그인해주세요.",
        "invalidCredentials": "잘못된 이메일 또는 비밀번호입니다.",
        "passwordMismatch": "비밀번호가 일치하지 않습니다.", "passwordTooShort": "비밀번호는 최소 8자 이상이어야 합니다.",
        "emailRequired": "이메일 주소는 필수입니다.", "passwordRequired": "비밀번호는 필수입니다.",
        "security": "보안 및 암호화", "authenticated": "인증 성공",
        "rememberMe": "로그인 상태 유지", "orContinueWith": "또는 다음으로 계속",
        "alreadyHaveAccount": "이미 계정이 있으신가요? 로그인", "dontHaveAccount": "계정이 없으신가요? 가입하기",
        "termsAgreement": "계속 진행하면 서비스 이용약관 및 개인정보 처리방침에 동의하게 됩니다.",
        "loginSuccess": "성역에 오신 것을 환영합니다.", "registrationSuccess": "계정이 성공적으로 생성되었습니다.",
        "logoutSuccess": "로그아웃되었습니다.", "passwordsDoNotMatch": "비밀번호가 일치하지 않습니다",
        "fillAllFields": "모든 필수 항목을 입력해주세요", "authRequired": "인증이 필요합니다",
        "signingIn": "로그인 중...", "creatingAccount": "계정 생성 중...",
        "profile": "프로필", "profileUpdated": "프로필이 업데이트되었습니다", "avatarUpdated": "프로필 이미지가 변경되었습니다",
        "newHere": "처음이신가요? 성역 보관소 생성", "logoutConfirm": "정말 로그아웃하시겠습니까?",
        "firewallActive": "방화벽 보안 보호 활성화됨", "firewallStatus": "WAF 및 요청 제한 정상 작동 중"
    },
    "dashboard": {
        "heroLine1": "고요함 속에서 비로소", "heroLine2": "눈에 보이지 않는", "heroLine3": "본질이 드러난다.",
        "heroTitle": "고요함 속에서 비로소 눈에 보이지 않는 본질이 드러난다.",
        "heroSub": "고요한 문턱을 넘어 Luminix로 들어오십시오: 60 FPS 컴퓨터 비전, 적응형 근력 프로토콜, 요가 정렬 및 Luna AI가 조화를 이루는 생체역학 성역.",
        "launchVision": "60 FPS 비전 시작 →", "startWorkout": "수련 시작하기 →",
        "chapterZero": "제00장 — 숨겨진 문 // 생체역학 성역",
        "thresholds": "문턱", "thresholdsDesc": "실시간 60 FPS 관절 추적 및 벡터 생체역학.",
        "stillGardens": "고요한 정원", "stillGardensDesc": "적응형 근력 운동 분할, 자동 반복 횟수 측정 및 휴식 주기.",
        "sacredCraft": "신성한 기술", "sacredCraftDesc": "{{count}}가지 가이드 요가 아사나 및 유지 시간 판정.",
        "nightRituals": "밤의 의식", "nightRitualsDesc": "대사 지능, BMR, TDEE 및 영양소 목표 매트릭스.",
        "peekSanmonStudio": "산문 — 60 FPS 비전 스튜디오",
        "sanmonHead": "그을린 편백, 마모된 돌, 초당 60프레임 시각 추적.",
        "sanmonLead": "Luminix는 육체와 알고리즘의 정밀함이 만나는 곳에서 시작됩니다: 클라우드 지연 없이 브라우저에서 직접 초당 60프레임으로 33개의 골격 랜드마크를 추적합니다. 벡터 기하학을 통해 관절 굴곡, 척추 편차, 어깨 기울기를 실시간으로 측정합니다.",
        "sanmonBody": "스쿼트, 오버헤드 프레스, 런지를 시청각 위험 경고와 함께 수행하십시오. 숨겨지는 것은 없습니다. 모든 키네마틱 각도가 실시간으로 표현됩니다.",
        "sanmonCta": "문턱 넘기 (실시간 자세 시작)",
        "statModules": "모듈", "statFps": "FPS 비전", "statYoga": "요가 아사나", "statIntelligence": "지능",
        "stillGardensApproach": "진입로", "stillGardensApproachMeta": "적응형 근력 분할 • 자동 반복수",
        "stillGardensApproachDesc": "5단계 생체역학 상태 머신, 자동 60초 휴식 타이머 및 근육 부위별 분할 루틴.",
        "stillGardensLanterns": "등불", "stillGardensLanternsMeta": "17가지 가이드 아사나 • 유지 타이머",
        "stillGardensLanternsDesc": "실시간 자세 검증, 목표 근육 강조 표시 및 카운트다운 유지 확인.",
        "stillGardensMoonwater": "달빛 물", "stillGardensMoonwaterMeta": "대사 매트릭스 • 영양 엔진",
        "stillGardensMoonwaterDesc": "임상 이중 BMR 공식, TDEE, 영양소 비율 목표 및 Gemini AI 자연어 식단 분석.",
        "sacredCraftHead": "여섯 가지 수련. 연결된 하나의 건강 지능.",
        "sacredCraftSub": "각 모듈은 독자적인 공학 분야로 작동하며, 통일된 생체 텔레메트리로 연결됩니다.",
        "craftVisionTitle": "생체역학 비전", "craftVisionDesc": "33개 관절 실시간 추적, 척추 경사 측정 및 위험 알림.", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "적응형 근력", "craftStrengthDesc": "부위별 근육 분할, 자동 카메라 반복수 측정 및 휴식 타이머.", "craftStrengthBadge": "{{count}}개 분할",
        "craftYogaTitle": "아사나 균형", "craftYogaDesc": "17가지 체계적 요가 포즈, 관절 각도 검증 및 유지 판정.", "craftYogaBadge": "{{count}}가지 자세",
        "craftBmiTitle": "대사의 연금술", "craftBmiDesc": "정밀 Mifflin-St Jeor 및 Harris-Benedict BMR, TDEE, 매크로 계산.", "craftBmiBadge": "임상 BMR",
        "craftFoodTitle": "일일 양생", "craftFoodDesc": "식사 기록, 수분 섭취 추적기 및 Gemini AI 식단 분석.", "craftFoodBadge": "Gemini AI",
        "craftOracleTitle": "신탁 (오라클)", "craftOracleDesc": "Luna AI 대화형 코칭, 부상 회복 조언 및 맞춤형 피트니스 계획.", "craftOracleBadge": "24/7 AI",
        "oracleHead": "훈련, 생체역학 또는 식단에 대해 Luna에게 물어보세요.",
        "oracleSub": "멀티 모델 Gemini를 기반으로 하는 Luna가 맞춤형 코칭, 키네마틱 자세 진단 및 대사 전략을 제공합니다.",
        "oraclePrompt1Title": "근비대 영양소 분할", "oraclePrompt1Desc": "점진적 과부하에 최적화된 단백질, 탄수화물, 지방 섭취 목표 계산.",
        "oraclePrompt2Title": "스쿼트 키네마틱 교정", "oraclePrompt2Desc": "무릎 굴곡 각도와 중립 척추 유지를 위한 생체역학 조언.",
        "oraclePrompt3Title": "7일 회복 식단 계획", "oraclePrompt3Desc": "조직 재생과 관절 가동성 향상을 촉진하는 항염증 영양 식단.",
        "oracleCta": "LUNA AI 대화 열기 →",
        "afterlightEyebrow": "제05장 — 여광 // 임상 서류",
        "afterlightTitle": "여광 (Afterlight)",
        "afterlightDesc": "문은 당신의 뒤에서 닫히지 않습니다. 어디서든 당신의 건강 데이터를 확인하십시오: 임상 PDF 보고서 출력, 이메일 전송 또는 HD 설명 비디오 생성.",
        "afterlightCta": "출력 스튜디오 열기",
        "faqEyebrow": "제05.5장 — 자주 묻는 질문", "faqTag": "質疑 // 임상 및 생체역학 질의응답",
        "faqHead": "생체역학적 정밀도 및 시스템 아키텍처.",
        "faqSub": "클라우드 없는 프라이버시, 60 FPS 비전 텔레메트리, 키네마틱 관절 및 임상 출력에 관한 모든 것.",
        "faqQ1": "Luminix는 영상 데이터를 서버로 보내지 않고 어떻게 60 FPS 비전을 유지합니까?",
        "faqA1": "Luminix는 WebAssembly(WASM) 및 WebGL 가속을 사용하여 브라우저 내부에서 100% 온디바이스로 MediaPipe 추론을 실행합니다. 외부 서버로 전송되는 픽셀은 전혀 없습니다.",
        "faqQ2": "33개 부위 생체역학 추적에 필요한 카메라 사양은 무엇입니까?",
        "faqA2": "일반적인 720p 또는 1080p 웹캠, 노트북 내장 카메라, 스마트폰 모바일 브라우저 카메라로 즉시 작동합니다.",
        "faqQ3": "적응형 근력 엔진은 어떻게 정확한 운동 반복수를 인식합니까?",
        "faqA3": "사지 벡터 내적을 측정하는 유한 상태 머신(FSM)을 사용합니다. 완전한 이완과 수축이 이루어졌을 때만 반복 횟수가 증가합니다.",
        "faqQ4": "기초대사량(BMR)과 영양소 비율은 어떻게 계산됩니까?",
        "faqA4": "임상적으로 검증된 Mifflin-St Jeor 및 Harris-Benedict 공식을 신체 활동 계수(PAL)와 결합하여 TDEE를 산출합니다.",
        "faqQ5": "임상 PDF 보고서와 데이터는 안전합니까?",
        "faqA5": "모든 출력 서류는 의료 지침을 준수하며, 로컬 데이터는 Argon2 암호화, JWT 세션 토큰 및 웹 방화벽(WAF)으로 보호됩니다.",
        "creatorEyebrow": "제06장 — 설계자", "creatorTag": "創造主 // 시스템 설계 및 제작",
        "creatorHead": "Ram Charan Teja가 확고한 철학으로 설계하고 제작했습니다.",
        "creatorSub": "Luminix의 이면에는 고주파 온디바이스 컴퓨터 비전, 임상 생체역학, 그리고 교토 사이버 미학을 융합하려는 열정이 있습니다.",
        "creatorRole": "풀스택 AI 시스템 아키텍트, 컴퓨터 비전 엔지니어. Luminix 생태계의 단독 제작자.",
        "creatorBio": "MediaPipe Vision • FastAPI 기반 • WebGL 및 Three.js • 멀티 모델 Gemini LLM • 키네마틱 삼각법 • 천여주박",
        "creatorViewDossier": "제작자 상세 포트폴리오 및 기술 스택 보기", "creatorSupportSanctuary": "제작자 후원하기"
    },
    "gym": {
        "title": "적응형 근력 엔진", "pageTitle": "근력 엔진 // 스마트 반복수 카운터",
        "moduleTag": "모듈 02 // 근력 프로토콜", "startWorkout": "운동 시작",
        "pauseWorkout": "일시 정지", "resumeWorkout": "다시 시작", "endWorkout": "운동 종료",
        "reps": "반복 횟수", "sets": "세트", "weight": "무게 (kg)", "restTimer": "휴식 타이머",
        "exercise": "운동 종목", "targetMuscles": "목표 근육", "formScore": "자세 점수",
        "repState": "운동 단계", "eccentric": "이완 (신장성)", "concentric": "수축 (단축성)", "lockout": "최대 신전",
        "depth": "가동 범위", "repPace": "템포", "nextExercise": "다음 종목", "workoutSummary": "운동 요약",
        "totalVolume": "총 볼륨", "completedSets": "완료한 세트", "averageForm": "평균 자세",
        "squat": "스쿼트", "pushup": "푸시업", "bicepCurl": "바이셉 컬", "overheadPress": "오버헤드 프레스", "lunge": "런지"
    },
    "luna": {
        "title": "Luna AI // 임상 건강 동반자", "pageTitle": "Luna AI — 생체역학 및 대사 상담 시스템",
        "moduleTag": "모듈 06 // 자율형 인공지능", "askLuna": "Luna에게 질문하기...",
        "askPlaceholder": "관절 각도, 부상 회복 또는 식단에 대해 물어보세요...",
        "send": "전송", "stop": "중지", "regenerate": "다시 생성", "clearChat": "대화 지우기",
        "newChat": "새 대화", "thinking": "Luna가 생리적 지표를 분석 중입니다...",
        "generating": "맞춤 조언을 작성하는 중입니다...", "suggestedQuestions": "추천 질문",
        "copy": "답변 복사", "copied": "클립보드에 복사되었습니다!", "error": "Luna AI 통신 오류",
        "retry": "다시 시도", "disclaimer": "Luna는 생체역학적 안내를 제공하며, 의사의 전문적인 진단을 대신하지 않습니다."
    },
    "notifications": {
        "title": "알림", "markAllAsRead": "모두 읽음으로 표시", "noNotifications": "새 알림이 없습니다",
        "savedSuccessfully": "성공적으로 저장되었습니다", "workoutCompleted": "운동이 완료되었습니다",
        "deviceConnected": "생체 측정 기기가 연결되었습니다", "profileUpdated": "프로필이 업데이트되었습니다",
        "languageChanged": "언어가 변경되었습니다", "analysisCompleted": "생체역학 분석이 완료되었습니다",
        "connectionFailed": "연결에 실패했습니다", "formWarning": "경고: 자세 기울어짐 감지됨",
        "repCounted": "정확한 반복수가 기록되었습니다", "restFinished": "휴식 종료 — 다음 세트 준비",
        "pdfGenerated": "임상 PDF 보고서가 생성되었습니다"
    },
    "nutrition": {
        "title": "대사 매트릭스 및 영양 엔진", "pageTitle": "대사 매트릭스 — 임상 BMR 및 TDEE",
        "moduleTag": "모듈 04 // 대사 지능", "bmr": "기초대사량 (BMR)",
        "tdee": "총 일일 에너지 소비량 (TDEE)", "calories": "칼로리", "protein": "단백질",
        "carbs": "탄수화물", "fats": "지방", "waterTracker": "수분 섭취 추적기", "addWater": "물 추가 (250 ml)",
        "targetWater": "목표 수분 섭취량", "mealLog": "식사 일지", "logMeal": "식사 기록하기",
        "foodAnalysis": "AI 식단 분석", "scanFood": "음식을 입력하거나 사진을 스캔...",
        "dietaryGoal": "식단 목표", "hypertrophy": "근육 증가 / 근비대",
        "cutting": "체지방 감소 / 다이어트", "maintenance": "현재 체중 유지", "macroBreakdown": "영양소 구성 비율"
    },
    "pose": {
        "title": "60 FPS 자세 엔진", "pageTitle": "실시간 자세 분석 (60 FPS) — 생체역학 키네마틱스",
        "moduleTag": "모듈 01 // 생체역학 키네마틱스", "poseAnalysis": "자세 분석",
        "startAnalysis": "분석 시작", "stopAnalysis": "분석 중지", "cameraPermissions": "카메라 권한 필요",
        "cameraInstructions": "60 FPS 동작 추적을 위해 카메라 접근 권한을 허용해주세요.",
        "grantAccess": "카메라 권한 허용", "bodyTracking": "신체 추적", "poseDetection": "자세 감지",
        "jointTracking": "관절 추적", "movementTracking": "동작 추적", "posture": "자세",
        "form": "운동 폼", "alignment": "신체 정렬", "riskDetection": "위험 감지", "riskLevel": "위험 수준",
        "movementQuality": "동작 완성도", "recommendations": "개선 권장사항", "warnings": "경고",
        "exerciseFeedback": "실시간 피드백", "analysisResults": "분석 결과", "confidence": "모델 신뢰도",
        "highRisk": "위험도 높음 — 자세를 즉시 교정하세요", "mediumRisk": "주의 — 관절 각도를 점검하세요",
        "lowRisk": "이상적인 생체역학적 자세", "safeForm": "안전한 폼", "jointAngles": "관절 각도",
        "toggleAngles": "각도 표시 전환", "toggleMirror": "카메라 화면 반전", "sessionDuration": "진행 시간",
        "alertCount": "경고 횟수", "fps": "초당 프레임 수 (FPS)", "processing": "분석 중..."
    },
    "settings": {
        "title": "시스템 설정", "profile": "생체 프로필", "account": "계정 관리",
        "language": "언어 / Language", "appearance": "화면 설정", "theme": "색상 테마",
        "darkMode": "다크 생크추어리 모드", "lightMode": "라이트 모드", "notifications": "알림 및 경고",
        "privacy": "완전한 프라이버시", "security": "보안 및 토큰", "connectedDevices": "연결된 센서",
        "healthDevices": "건강 측정 기기", "data": "데이터 내보내기", "aiSettings": "AI 환경설정",
        "logout": "로그아웃", "deleteAccount": "계정 영구 삭제",
        "deleteAccountConfirm": "계정과 모든 로컬 생체 측정 데이터를 영구적으로 삭제하시겠습니까?",
        "saveChanges": "변경사항 저장", "changesSaved": "설정이 성공적으로 저장되었습니다.",
        "fullName": "이름", "age": "나이", "bodyWeight": "체중 (kg)", "heightCm": "신장 (cm)",
        "gender": "성별", "selectGender": "성별 선택", "primaryGoal": "주요 건강 목표",
        "hypertrophy": "근육 비대 및 근력 증가", "fatLoss": "체지방 감량 및 정의", "biomechanics": "자세 교정 및 가동성",
        "endurance": "심폐 지구력 향상", "customProfilePicture": "프로필 사진",
        "storedSecurely": "브라우저 로컬 금고에 안전하게 암호화 보관됨", "selectAvatarImage": "이미지 선택",
        "saveInitialize": "저장 및 시스템 초기화", "personalizeSanctuary": "나만의 성역 맞춤 설정",
        "sanctuaryWord": "성역", "biometricRegistry": "생체 등록부",
        "biometricDescription": "입력된 신체 지표는 60 FPS 비전 추적 및 대사 계산을 정밀하게 보정합니다."
    },
    "yoga": {
        "title": "17가지 신성한 요가 아사나", "pageTitle": "요가 // 심신 평정의 방",
        "moduleTag": "모듈 03 // 평정", "pose": "아사나 자세", "breathing": "호흡법",
        "duration": "유지 시간", "difficulty": "난이도", "instructions": "정렬 안내",
        "startSession": "수련 시작", "endSession": "수련 종료", "beginner": "초급",
        "intermediate": "중급", "advanced": "고급", "safetyWarnings": "관절 안전 주의사항",
        "recommendations": "균형 조언", "progress": "진행률", "holdTime": "현재 유지 시간",
        "holdDuration": "목표 유지 시간", "poseGuide": "자세 가이드", "alignmentTips": "정렬 팁",
        "benefits": "신체적 이점", "asanaLibrary": "전체 아사나 목록", "selectedPose": "선택된 아사나",
        "formAccuracy": "자세 정확도", "breathingPattern": "호흡 주기",
        "inhale": "숨 들이쉬기", "exhale": "숨 내쉬기", "hold": "숨 참기", "relax": "긴장 풀기"
    }
}

# Write ja.py, ko.py
with open(LOCALES_DATA_DIR / "ja.py", "w", encoding="utf-8") as f:
    f.write('"""Japanese (ja) translation module for Luminix."""\n\nJA_TRANSLATIONS = ' + repr(JA_TRANSLATIONS) + '\n')
print(f"Generated ja.py with {sum(len(v) for v in JA_TRANSLATIONS.values())} keys")

with open(LOCALES_DATA_DIR / "ko.py", "w", encoding="utf-8") as f:
    f.write('"""Korean (ko) translation module for Luminix."""\n\nKO_TRANSLATIONS = ' + repr(KO_TRANSLATIONS) + '\n')
print(f"Generated ko.py with {sum(len(v) for v in KO_TRANSLATIONS.values())} keys")
