#!/usr/bin/env python3
"""
Comprehensive Localization Generator for:
- fr (French)
- ru (Russian)
- pt (Portuguese)
- ja (Japanese)
- ko (Korean)
- it (Italian)
- fil (Filipino / Tagalog)

Outputs pure python modules into scripts/locales_data/
"""

import sys
from pathlib import Path

LOCALES_DATA_DIR = Path(__file__).resolve().parent / "locales_data"
LOCALES_DATA_DIR.mkdir(parents=True, exist_ok=True)

# 1. FRENCH (fr)
FR_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "Système d'exploitation autonome de santé et biomécanique par IA", "version": "v4.3",
        "save": "Enregistrer", "cancel": "Annuler", "confirm": "Confirmer", "delete": "Supprimer", "edit": "Modifier",
        "continue": "Continuer", "back": "Retour", "next": "Suivant", "start": "Démarrer", "stop": "Arrêter",
        "retry": "Réessayer", "close": "Fermer", "search": "Rechercher", "loading": "Chargement...",
        "processing": "Traitement en cours...", "success": "Succès", "failed": "Échec", "error": "Erreur",
        "noData": "Aucune donnée disponible", "noResults": "Aucun résultat trouvé",
        "somethingWentWrong": "Une erreur est survenue", "tryAgain": "Veuillez réessayer", "yes": "Oui", "no": "Non",
        "ok": "OK", "submit": "Soumettre", "reset": "Réinitialiser", "download": "Télécharger", "upload": "Téléverser",
        "share": "Partager", "copyLink": "Copier le lien", "copied": "Copié !", "viewMore": "Voir plus",
        "viewLess": "Voir moins", "learnMore": "En savoir plus", "explore": "Explorer", "skipForNow": "Passer pour l'instant",
        "accept": "Accepter", "decline": "Refuser", "send": "Envoyer", "transmit": "Transmettre la télémétrie →",
        "scrollToTop": "Haut de page", "contact": "Contact", "exploreSystem": "Explorer le système ↓",
        "exploreSanctuary": "Explorer le sanctuaire ↓", "scrollToEnter": "Défiler pour entrer", "breadcrumbSanctuary": "Sanctuaire",
        "breadcrumbModules": "Modules", "skipToContent": "Passer au contenu principal", "details": "Détails",
        "refresh": "Actualiser", "clear": "Effacer", "filter": "Filtrer", "sort": "Trier", "all": "Tous",
        "none": "Aucun", "select": "Sélectionner", "selected": "Sélectionné", "dismiss": "Ignorer",
        "searchChambersPlaceholder": "Rechercher chambres, disciplines et systèmes... (⌘K)", "navigate": "Naviguer",
        "bannerRelease": "Édition Printemps de Kyoto",
        "bannerDetails": "— Télémétrie 60 FPS de posture par caméra et compteur de répétitions intelligent v4.3 activés.",
        "footerTagline": "Une promenade nocturne à travers la biomécanique de Kyoto. Cyprès calciné, lueur de lanterne et lune vermeille rendue en direct en WebGL.",
        "footerChapters": "Chapitres", "footerDisciplines": "Disciplines", "footerIntelligence": "Intelligence",
        "footerSovereignty": "Souveraineté", "footerHeroLink": "Le Seuil", "footerGateLink": "La Porte Sanmon",
        "footerPathwaysLink": "Jardins Paisibles", "footerLessonsLink": "Art Sacré", "footerEternityLink": "Lueur Postérieure",
        "footerFaqLink": "Questions Fréquentes", "footerCreatorLink": "L'Architecte", "footerLivePoseLink": "Posture Directe 60 FPS",
        "footerGymLink": "Moteur Musculaire Adaptatif", "footerYogaLink": "17 Asanas de Yoga", "footerBmiLink": "Matrice Métabolique",
        "footerFoodLink": "Nutrition & Hydratation", "footerLunaLink": "Compagne IA Luna", "footerExportLink": "Export Dossier PDF Médical",
        "footerDocsLink": "Documentation FastAPI Swagger", "footerHealthLink": "État du Pare-Feu", "footerShareLink": "📢 Partager la plateforme",
        "footerZeroLeakLink": "Confidentialité Zéro-Fuite", "footerTermsLink": "Conditions d'utilisation",
        "footerAccessibilityLink": "Déclaration d'accessibilité", "footerCookieSettingsLink": "Préférences de cookies",
        "footerRobotsLink": "Index Robots", "footerCopyright": "© 2026 LUMINIX — INGÉNIERIE ÉDITORIALE DE KYOTO",
        "footerBuildInfo": "DERNIÈRE MISE À JOUR : 6 SEPTEMBRE 2026 // BUILD 4.3-PROD",
        "footerPhilosophy": "Le silence est une discipline • Intelligence corporelle",
        "privacy": "CONFIDENTIALITÉ", "terms": "CONDITIONS", "accessibility": "ACCESSIBILITÉ"
    },
    "auth": {
        "login": "Connexion", "register": "S'inscrire", "signIn": "SE CONNECTER", "signOut": "Se déconnecter",
        "sanctuaryMember": "Membre du Sanctuaire", "guest": "Invité", "user": "Utilisateur", "member": "Membre",
        "viewProfileTitle": "Voir profil utilisateur & biométrie", "enterSanctuary": "Entrer dans le sanctuaire",
        "createAccount": "Créer un compte", "email": "Adresse e-mail", "password": "Mot de passe",
        "confirmPassword": "Confirmer le mot de passe", "forgotPassword": "Mot de passe oublié ?",
        "resetPassword": "Réinitialiser le mot de passe", "welcomeBack": "Bon retour parmi nous",
        "sessionExpired": "Session expirée. Veuillez vous reconnecter.",
        "invalidCredentials": "Adresse e-mail ou mot de passe incorrect.",
        "passwordMismatch": "Les mots de passe ne correspondent pas.",
        "passwordTooShort": "Le mot de passe doit comporter au moins 8 caractères.",
        "emailRequired": "L'adresse e-mail est obligatoire.", "passwordRequired": "Le mot de passe est obligatoire.",
        "security": "Sécurité & Chiffrement", "authenticated": "Authentifié avec succès",
        "rememberMe": "Se souvenir de moi", "orContinueWith": "Ou continuer avec",
        "alreadyHaveAccount": "Vous avez déjà un compte ? Connexion", "dontHaveAccount": "Pas encore de compte ? S'inscrire",
        "termsAgreement": "En continuant, vous acceptez nos conditions de service et notre politique de confidentialité.",
        "loginSuccess": "Bienvenue dans le sanctuaire.", "registrationSuccess": "Compte créé avec succès.",
        "logoutSuccess": "Déconnexion réussie.", "passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
        "fillAllFields": "Veuillez remplir tous les champs obligatoires", "authRequired": "Authentification requise",
        "signingIn": "Connexion en cours...", "creatingAccount": "Création du compte...",
        "profile": "Profil", "profileUpdated": "Profil mis à jour avec succès", "avatarUpdated": "Avatar mis à jour",
        "newHere": "Nouveau ? Créer un coffre de sanctuaire", "logoutConfirm": "Voulez-vous vraiment vous déconnecter ?",
        "firewallActive": "Protection par pare-feu active", "firewallStatus": "WAF & Limitation de débit opérationnels"
    },
    "dashboard": {
        "heroLine1": "Là où le silence révèle", "heroLine2": "ce que les yeux", "heroLine3": "ne peuvent percevoir.",
        "heroTitle": "Là où le silence révèle ce que les yeux ne peuvent percevoir.",
        "heroSub": "Pénétrez dans Luminix à travers ses seuils silencieux : un sanctuaire intelligent de vision par ordinateur 60 FPS, de force adaptative, d'alignement yoga et d'IA Luna.",
        "launchVision": "LANCER LA VISION 60 FPS →", "startWorkout": "COMMENCER L'ENTRAÎNEMENT →",
        "chapterZero": "CHAPITRE 00 — LA PORTE SECRÈTE // SANCTUAIRE BIOMÉCANIQUE",
        "thresholds": "SEUILS", "thresholdsDesc": "Suivi articulaire 60 FPS en temps réel et biomécanique vectorielle.",
        "stillGardens": "JARDINS PAISIBLES", "stillGardensDesc": "Protocoles de musculation adaptatifs, compteur de répétitions et temps de repos.",
        "sacredCraft": "ART SACRÉ", "sacredCraftDesc": "{{count}} asanas de yoga guidées avec contrôle de durée de maintien.",
        "nightRituals": "RITUELS NOCTURNES", "nightRitualsDesc": "Intelligence métabolique, BMR, TDEE et matrices de macronutriments.",
        "peekSanmonStudio": "SANMON — Studio de Vision 60 FPS",
        "sanmonHead": "Cyprès calciné, pierre polie, vision 60 FPS en temps réel.",
        "sanmonLead": "Luminix commence là où le corps physique rencontre la précision algorithmique : 33 repères squelettiques suivis à 60 images par seconde directement dans le navigateur sans latence cloud. La géométrie vectorielle mesure la flexion articulaire, l'axe vertébral et l'inclinaison des épaules en temps réel.",
        "sanmonBody": "Enchaînez squats, développés militaires ou fentes avec des indicateurs de risque visuels et sonores instantanés. Rien n'est masqué. Chaque degré cinématique est retranscrit en direct.",
        "sanmonCta": "Franchir le seuil (Lancer la posture en direct)",
        "statModules": "Modules", "statFps": "FPS Vision", "statYoga": "Asanas Yoga", "statIntelligence": "Intelligence",
        "stillGardensApproach": "Approche", "stillGardensApproachMeta": "Splits Musculaires Adaptatifs • Répétitions Auto",
        "stillGardensApproachDesc": "Machine à états biomécanique en 5 phases, intervalles de repos automatisés de 60s et ciblages musculaires.",
        "stillGardensLanterns": "Lanternes", "stillGardensLanternsMeta": "17 Asanas Guidées • Chronomètre de Maintien",
        "stillGardensLanternsDesc": "Validation posturale en temps réel, surbrillance des muscles cibles et décompte précis de maintien.",
        "stillGardensMoonwater": "Clair de Lune", "stillGardensMoonwaterMeta": "Matrice Métabolique • Moteur Nutritionnel",
        "stillGardensMoonwaterDesc": "Doubles formules BMR cliniques, calcul TDEE, ratios macro et analyse alimentaire naturelle par IA Gemini.",
        "sacredCraftHead": "Six disciplines. Une intelligence de santé connectée.",
        "sacredCraftSub": "Chaque module fonctionne comme une discipline d'ingénierie autonome, unie par une télémétrie biométrique standardisée.",
        "craftVisionTitle": "Vision Biomécanique", "craftVisionDesc": "Suivi en direct de 33 articulations, inclinaison rachidienne et alarmes de risque.", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "Force Adaptative", "craftStrengthDesc": "Programmes musculaires ciblés, comptage automatique de répétitions et chronomètre.", "craftStrengthBadge": "{{count}} Programmes",
        "craftYogaTitle": "Équilibre Asana", "craftYogaDesc": "17 postures de yoga structurées avec validation d'angles articulaires.", "craftYogaBadge": "{{count}} Postures",
        "craftBmiTitle": "Alchimie Métabolique", "craftBmiDesc": "Formules cliniques précises Mifflin-St Jeor et Harris-Benedict, TDEE et macros.", "craftBmiBadge": "BMR Clinique",
        "craftFoodTitle": "Subsistance Quotidienne", "craftFoodDesc": "Journal de repas, suivi d'hydratation et analyse nutritionnelle par IA.", "craftFoodBadge": "IA Gemini",
        "craftOracleTitle": "L'Oracle", "craftOracleDesc": "Coaching conversationnel Luna IA, conseils de récupération articulaire et plans sur mesure.", "craftOracleBadge": "IA 24/7",
        "oracleHead": "Interrogez Luna sur votre entraînement, votre biomécanique ou votre nutrition.",
        "oracleSub": "Propulsée par des modèles Gemini avancés, Luna offre un accompagnement personnalisé, des diagnostics de posture et des stratégies énergétiques.",
        "oraclePrompt1Title": "Répartition Macros Hypertrophie", "oraclePrompt1Desc": "Calculez vos cibles en protéines, glucides et lipides pour la surcharge progressive.",
        "oraclePrompt2Title": "Correction Cinématique Squat", "oraclePrompt2Desc": "Conseils biomécaniques pour optimiser la flexion des genoux et préserver le dos.",
        "oraclePrompt3Title": "Diète Récupération 7 Jours", "oraclePrompt3Desc": "Aliments anti-inflammatoires pour accélérer la réparation tissulaire et la souplesse articulaire.",
        "oracleCta": "OUVRIR LA CONVERSATION LUNA IA →",
        "afterlightEyebrow": "Chapitre 05 — Lueur Postérieure // Dossier Clinique",
        "afterlightTitle": "Lueur Postérieure",
        "afterlightDesc": "Le portail ne se referme pas derrière vous. Emportez votre intelligence de santé partout : exportez des rapports cliniques PDF, envoyez des dossiers par e-mail ou générez des synthèses vidéo HD.",
        "afterlightCta": "Ouvrir le studio d'exportation",
        "faqEyebrow": "Chapitre 05.5 — Questions Fréquentes", "faqTag": "質疑 // FAQS CLINIQUES & BIOMÉCANIQUES",
        "faqHead": "Précision biomécanique et architecture du système.",
        "faqSub": "Tout ce que vous devez savoir sur la confidentialité sans serveur, la télémétrie 60 FPS, les articulations cinématiques et les exports cliniques.",
        "faqQ1": "Comment Luminix assure-t-il une vision 60 FPS sans envoyer de flux vidéo à des serveurs ?",
        "faqA1": "Luminix exécute 100% de l'inférence MediaPipe localement dans votre navigateur via WebAssembly (WASM) et l'accélération matérielle WebGL. Aucun pixel n'est jamais téléversé.",
        "faqQ2": "Quel matériel de caméra est requis pour la biomécanique à 33 points ?",
        "faqA2": "Toute webcam standard 720p ou 1080p, caméra intégrée d'ordinateur portable ou caméra mobile fonctionne nativement avec lissage adaptatif.",
        "faqQ3": "Comment le moteur de musculation détecte-t-il les répétitions ?",
        "faqA3": "Il utilise une machine à états finis (FSM) mesurant les produits scalaires vectoriels entre segments osseux. Les répétitions ne sont comptées qu'en amplitude complète.",
        "faqQ4": "Comment le taux métabolique de base (BMR) est-il calculé ?",
        "faqA4": "Nous appliquons les équations cliniques validées de Mifflin-St Jeor et Harris-Benedict, indexées sur votre facteur d'activité (PAL).",
        "faqQ5": "Les rapports PDF cliniques et les données sont-ils sécurisés ?",
        "faqA5": "Oui. Les données sont chiffrées localement et protégées par Argon2, des jetons JWT et notre pare-feu applicatif (WAF).",
        "creatorEyebrow": "Chapitre 06 — L'Architecte", "creatorTag": "創造主 // CONCEPTEUR & VISION",
        "creatorHead": "Conçu par Ram Charan Teja avec une vision intransigeante.",
        "creatorSub": "Luminix est né d'une passion : fusionner vision par ordinateur haute fréquence côté client, rigueur biomécanique et esthétique cyber-Kyoto.",
        "creatorRole": "Architecte Systèmes IA Full-Stack, Ingénieur Vision par Ordinateur. Créateur exclusif de l'écosystème Luminix.",
        "creatorBio": "MediaPipe Vision • Architecture FastAPI • WebGL & Three.js • LLM Gemini Multi-Modèles • Trigonométrie Cinématique",
        "creatorViewDossier": "Consulter le dossier complet et l'arsenal technologique", "creatorSupportSanctuary": "Soutenir le créateur"
    },
    "gym": {
        "title": "Moteur Musculaire Adaptatif", "pageTitle": "Moteur Musculaire // Compteur Intelligent de Répétitions",
        "moduleTag": "MODULE 02 // PROTOCOLES DE FORCE", "startWorkout": "Démarrer l'entraînement",
        "pauseWorkout": "Mettre en pause", "resumeWorkout": "Reprendre", "endWorkout": "Terminer la séance",
        "reps": "Répétitions", "sets": "Séries", "weight": "Charge (kg)", "restTimer": "Repos",
        "exercise": "Exercice", "targetMuscles": "Muscles ciblés", "formScore": "Score de forme",
        "repState": "Phase", "eccentric": "Excentrique", "concentric": "Concentrique", "lockout": "Verrouillage",
        "depth": "Profondeur", "repPace": "Cadence", "nextExercise": "Exercice suivant", "workoutSummary": "Résumé d'entraînement",
        "totalVolume": "Volume total", "completedSets": "Séries complétées", "averageForm": "Forme moyenne",
        "squat": "Squat", "pushup": "Pompes", "bicepCurl": "Curl Biceps", "overheadPress": "Développé Épaules", "lunge": "Fente"
    },
    "luna": {
        "title": "Luna IA // Compagne Clinique", "pageTitle": "Luna IA — Dialogue Biomécanique & Métabolique",
        "moduleTag": "MODULE 06 // INTELLIGENCE AUTONOME", "askLuna": "Demandez à Luna...",
        "askPlaceholder": "Posez vos questions sur la biomécanique, les angles articulaires ou la nutrition...",
        "send": "Envoyer", "stop": "Arrêter", "regenerate": "Régénérer", "clearChat": "Effacer l'historique",
        "newChat": "Nouvelle conversation", "thinking": "Luna analyse vos données physiologiques...",
        "generating": "Formulation des conseils en cours...", "suggestedQuestions": "Questions suggérées",
        "copy": "Copier la réponse", "copied": "Copié dans le presse-papiers !", "error": "Erreur de communication avec Luna",
        "retry": "Réessayer", "disclaimer": "Luna fournit des orientations biomécaniques, mais ne remplace pas un avis médical."
    },
    "notifications": {
        "title": "Notifications", "markAllAsRead": "Tout marquer comme lu", "noNotifications": "Aucune nouvelle notification",
        "savedSuccessfully": "Enregistré avec succès", "workoutCompleted": "Séance d'entraînement terminée",
        "deviceConnected": "Appareil biométrique connecté", "profileUpdated": "Profil mis à jour avec succès",
        "languageChanged": "Langue modifiée avec succès", "analysisCompleted": "Analyse biomécanique terminée",
        "connectionFailed": "Échec de connexion", "formWarning": "Attention : déviation posturale détectée",
        "repCounted": "Répétition enregistrée", "restFinished": "Temps de repos terminé — Prêt pour la série",
        "pdfGenerated": "Dossier médical PDF généré avec succès"
    },
    "nutrition": {
        "title": "Matrice Métabolique & Moteur Nutritionnel", "pageTitle": "Matrice Métabolique — BMR Clinique & TDEE",
        "moduleTag": "MODULE 04 // INTELLIGENCE MÉTABOLIQUE", "bmr": "BMR (Métabolisme de Base)",
        "tdee": "Dépense Énergétique Totale (TDEE)", "calories": "Calories", "protein": "Protéines",
        "carbs": "Glucides", "fats": "Lipides", "waterTracker": "Suivi d'Hydratation", "addWater": "Ajouter de l'eau (250 ml)",
        "targetWater": "Objectif hydratation", "mealLog": "Journal Alimentaire", "logMeal": "Enregistrer un repas",
        "foodAnalysis": "Analyse Alimentaire par IA", "scanFood": "Décrire ou scanner un aliment...",
        "dietaryGoal": "Objectif diététique", "hypertrophy": "Prise de masse / Hypertrophie",
        "cutting": "Sèche / Perte de gras", "maintenance": "Maintien du poids", "macroBreakdown": "Répartition des macros"
    },
    "pose": {
        "title": "Moteur de Posture 60 FPS", "pageTitle": "Posture en Direct (60 FPS) — Cinématique Biomécanique",
        "moduleTag": "MODULE 01 // CINÉMATIQUE BIOMÉCANIQUE", "poseAnalysis": "Analyse de posture",
        "startAnalysis": "Démarrer l'analyse", "stopAnalysis": "Arrêter l'analyse", "cameraPermissions": "Autorisation caméra requise",
        "cameraInstructions": "Veuillez autoriser l'accès à la caméra pour le suivi postural 60 FPS.",
        "grantAccess": "Accorder l'accès caméra", "bodyTracking": "Suivi corporel", "poseDetection": "Détection de posture",
        "jointTracking": "Suivi articulaire", "movementTracking": "Suivi du mouvement", "posture": "Posture",
        "form": "Forme", "alignment": "Alignement", "riskDetection": "Détection de risque", "riskLevel": "Niveau de risque",
        "movementQuality": "Qualité du mouvement", "recommendations": "Conseils", "warnings": "Avertissements",
        "exerciseFeedback": "Retour en direct", "analysisResults": "Résultats d'analyse", "confidence": "Confiance du modèle",
        "highRisk": "Risque élevé — Corriger la posture", "mediumRisk": "Risque modéré — Ajuster l'angle",
        "lowRisk": "Forme biomécanique optimale", "safeForm": "Exécution sécurisée", "jointAngles": "Angles articulaires",
        "toggleAngles": "Afficher les angles", "toggleMirror": "Inverser miroir caméra", "sessionDuration": "Durée de session",
        "alertCount": "Alertes de posture", "fps": "Images/s (FPS)", "processing": "Traitement..."
    },
    "settings": {
        "title": "Paramètres du Système", "profile": "Profil Biométrique", "account": "Gestion du Compte",
        "language": "Langue / Language", "appearance": "Apparence", "theme": "Thème visuel",
        "darkMode": "Mode Sanctuaire Sombre", "lightMode": "Mode Clair", "notifications": "Notifications & Alertes",
        "privacy": "Confidentialité Souveraine", "security": "Sécurité & Jetons", "connectedDevices": "Capteurs Connectés",
        "healthDevices": "Montres & Trackers", "data": "Export & Coffre-fort", "aiSettings": "Paramètres IA",
        "logout": "Déconnexion", "deleteAccount": "Supprimer définitivement le compte",
        "deleteAccountConfirm": "Voulez-vous vraiment supprimer votre compte et toutes vos données biométriques locales ?",
        "saveChanges": "Enregistrer les modifications", "changesSaved": "Paramètres enregistrés avec succès.",
        "fullName": "Nom complet", "age": "Âge", "bodyWeight": "Poids corporel (kg)", "heightCm": "Taille (cm)",
        "gender": "Genre", "selectGender": "Sélectionner le genre", "primaryGoal": "Objectif de santé principal",
        "hypertrophy": "Hypertrophie musculaire", "fatLoss": "Perte de masse grasse", "biomechanics": "Mobilité & Posture",
        "endurance": "Endurance cardiorespiratoire", "customProfilePicture": "Photo de profil",
        "storedSecurely": "Chiffré localement dans votre coffre-fort navigateur", "selectAvatarImage": "Choisir une image",
        "saveInitialize": "Enregistrer & Initialiser", "personalizeSanctuary": "Personnalisez votre sanctuaire",
        "sanctuaryWord": "Sanctuaire", "biometricRegistry": "Registre Biométrique",
        "biometricDescription": "Vos paramètres physiologiques calibrent la vision 60 FPS et les calculs métaboliques."
    },
    "yoga": {
        "title": "17 Asanas de Yoga Sacrées", "pageTitle": "Yoga // Chambre d'Équilibre et Sérénité",
        "moduleTag": "MODULE 03 // ÉQUILIBRE", "pose": "Posture Asana", "breathing": "Respiration",
        "duration": "Durée", "difficulty": "Difficulté", "instructions": "Instructions d'alignement",
        "startSession": "Démarrer la session", "endSession": "Terminer la session", "beginner": "Débutant",
        "intermediate": "Intermédiaire", "advanced": "Avancé", "safetyWarnings": "Avertissements articulaires",
        "recommendations": "Conseils d'équilibre", "progress": "Progression", "holdTime": "Temps maintenu",
        "holdDuration": "Maintien cible", "poseGuide": "Guide de posture", "alignmentTips": "Astuces d'alignement",
        "benefits": "Bienfaits physiologiques", "asanaLibrary": "Bibliothèque complète des Asanas",
        "selectedPose": "Posture sélectionnée", "formAccuracy": "Précision d'alignement", "breathingPattern": "Rythme respiratoire",
        "inhale": "Inspiration", "exhale": "Expiration", "hold": "Rétention", "relax": "Relâchement"
    }
}

# 2. RUSSIAN (ru)
RU_TRANSLATIONS = {
    "common": {
        "appName": "LUMINIX", "tagline": "Автономная ИИ-система здоровья и биомеханики", "version": "v4.3",
        "save": "Сохранить", "cancel": "Отмена", "confirm": "Подтвердить", "delete": "Удалить", "edit": "Редактировать",
        "continue": "Продолжить", "back": "Назад", "next": "Далее", "start": "Начать", "stop": "Остановить",
        "retry": "Повторить", "close": "Закрыть", "search": "Поиск", "loading": "Загрузка...",
        "processing": "Обработка...", "success": "Успешно", "failed": "Ошибка", "error": "Ошибка",
        "noData": "Нет доступных данных", "noResults": "Результатов не найдено",
        "somethingWentWrong": "Что-то пошло не так", "tryAgain": "Попробуйте снова", "yes": "Да", "no": "Нет",
        "ok": "OK", "submit": "Отправить", "reset": "Сбросить", "download": "Скачать", "upload": "Загрузить",
        "share": "Поделиться", "copyLink": "Скопировать ссылку", "copied": "Скопировано!", "viewMore": "Подробнее",
        "viewLess": "Свернуть", "learnMore": "Узнать больше", "explore": "Исследовать", "skipForNow": "Пропустить",
        "accept": "Принять", "decline": "Отклонить", "send": "Отправить", "transmit": "Передать телеметрию →",
        "scrollToTop": "Наверх", "contact": "Контакты", "exploreSystem": "Исследовать систему ↓",
        "exploreSanctuary": "Исследовать святилище ↓", "scrollToEnter": "Прокрутите для входа", "breadcrumbSanctuary": "Святилище",
        "breadcrumbModules": "Модули", "skipToContent": "Перейти к основному содержимому", "details": "Детали",
        "refresh": "Обновить", "clear": "Очистить", "filter": "Фильтр", "sort": "Сортировка", "all": "Все",
        "none": "Нет", "select": "Выбрать", "selected": "Выбрано", "dismiss": "Закрыть",
        "searchChambersPlaceholder": "Поиск по палатам, дисциплинам и системам... (⌘K)", "navigate": "Навигация",
        "bannerRelease": "Весенний релиз в Киото",
        "bannerDetails": "— Компьютерное зрение 60 FPS для анализа позы и умный счетчик повторений v4.3 запущены.",
        "footerTagline": "Ночная прогулка по биомеханике Киото. Обожженный кипарис, свет фонарей и алая луна в живом WebGL.",
        "footerChapters": "Главы", "footerDisciplines": "Дисциплины", "footerIntelligence": "Интеллект",
        "footerSovereignty": "Суверенитет", "footerHeroLink": "Порог", "footerGateLink": "Врата Санмон",
        "footerPathwaysLink": "Тихие сады", "footerLessonsLink": "Священное мастерство", "footerEternityLink": "Послесвечение",
        "footerFaqLink": "Частые вопросы", "footerCreatorLink": "Архитектор", "footerLivePoseLink": "Живая поза 60 FPS",
        "footerGymLink": "Адаптивный силовой модуль", "footerYogaLink": "17 асан йоги", "footerBmiLink": "Метаболическая матрица",
        "footerFoodLink": "Питание и гидратация", "footerLunaLink": "ИИ-ассистент Luna", "footerExportLink": "Экспорт медкарты в PDF",
        "footerDocsLink": "Документация FastAPI Swagger", "footerHealthLink": "Статус файрвола", "footerShareLink": "📢 Поделиться платформой",
        "footerZeroLeakLink": "Конфиденциальность без утечек", "footerTermsLink": "Условия использования",
        "footerAccessibilityLink": "Заявление о доступности", "footerCookieSettingsLink": "Настройки cookie",
        "footerRobotsLink": "Индекс Robots", "footerCopyright": "© 2026 LUMINIX — KYOTO EDITORIAL ENGINEERING",
        "footerBuildInfo": "ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: 6 СЕНТЯБРЯ 2026 // BUILD 4.3-PROD",
        "footerPhilosophy": "Тишина — это дисциплина • Интеллект тела",
        "privacy": "КОНФИДЕНЦИАЛЬНОСТЬ", "terms": "УСЛОВИЯ", "accessibility": "ДОСТУПНОСТЬ"
    },
    "auth": {
        "login": "Вход", "register": "Регистрация", "signIn": "ВОЙТИ", "signOut": "Выйти",
        "sanctuaryMember": "Член Святилища", "guest": "Гость", "user": "Пользователь", "member": "Участник",
        "viewProfileTitle": "Профиль и биометрия", "enterSanctuary": "Войти в святилище",
        "createAccount": "Создать аккаунт", "email": "Электронная почта", "password": "Пароль",
        "confirmPassword": "Подтвердите пароль", "forgotPassword": "Забыли пароль?",
        "resetPassword": "Сбросить пароль", "welcomeBack": "С возвращением",
        "sessionExpired": "Срок сессии истек. Пожалуйста, войдите снова.",
        "invalidCredentials": "Неверный адрес электронной почты или пароль.",
        "passwordMismatch": "Пароли не совпадают.", "passwordTooShort": "Пароль должен содержать не менее 8 символов.",
        "emailRequired": "Требуется адрес электронной почты.", "passwordRequired": "Требуется пароль.",
        "security": "Безопасность и шифрование", "authenticated": "Успешно авторизован",
        "rememberMe": "Запомнить меня", "orContinueWith": "Или продолжить через",
        "alreadyHaveAccount": "Уже есть аккаунт? Войти", "dontHaveAccount": "Нет аккаунта? Зарегистрироваться",
        "termsAgreement": "Продолжая, вы принимаете Условия использования и Политику конфиденциальности.",
        "loginSuccess": "Добро пожаловать в святилище.", "registrationSuccess": "Аккаунт успешно создан.",
        "logoutSuccess": "Вы успешно вышли.", "passwordsDoNotMatch": "Пароли не совпадают",
        "fillAllFields": "Заполните все обязательные поля", "authRequired": "Требуется авторизация",
        "signingIn": "Выполняется вход...", "creatingAccount": "Создание аккаунта...",
        "profile": "Профиль", "profileUpdated": "Профиль успешно обновлен", "avatarUpdated": "Аватар обновлен",
        "newHere": "Впервые здесь? Создать хранилище святилища", "logoutConfirm": "Вы уверены, что хотите выйти?",
        "firewallActive": "Защита файрвола активна", "firewallStatus": "WAF и ограничение запросов работают"
    },
    "dashboard": {
        "heroLine1": "Где тишина раскрывает то,", "heroLine2": "чего не видят", "heroLine3": "глаза.",
        "heroTitle": "Где тишина раскрывает то, чего не видят глаза.",
        "heroSub": "Войдите в Luminix через тихие врата: интеллектуальное святилище компьютерного зрения 60 FPS, адаптивной силы, йогической гармонии и ИИ Luna.",
        "launchVision": "ЗАПУСТИТЬ ЗРЕНИЕ 60 FPS →", "startWorkout": "НАЧАТЬ ТРЕНИРОВКУ →",
        "chapterZero": "ГЛАВА 00 — ТАЙНЫЕ ВРАТА // БИОМЕХАНИЧЕСКОЕ СВЯТИЛИЩЕ",
        "thresholds": "ПОРОГИ", "thresholdsDesc": "Отслеживание суставов в реальном времени при 60 FPS и векторная биомеханика.",
        "stillGardens": "ТИХИЕ САДЫ", "stillGardensDesc": "Адаптивные сплиты силовых тренировок, автосчетчик повторений и интервалы отдыха.",
        "sacredCraft": "СВЯЩЕННОЕ МАСТЕРСТВО", "sacredCraftDesc": "{{count}} пошаговых асан йоги с проверкой времени удержания позы.",
        "nightRituals": "НОЧНЫЕ РИТУАЛЫ", "nightRitualsDesc": "Метаболический интеллект, BMR, TDEE и матрицы макронутриентов.",
        "peekSanmonStudio": "САНМОН — Студия зрения 60 FPS",
        "sanmonHead": "Обожженный кипарис, потертый камень, зрение 60 кадров/с.",
        "sanmonLead": "Luminix начинается там, где физическое тело встречается с алгоритмической точностью: 33 ключевые точки скелета отслеживаются со скоростью 60 кадров в секунду прямо в браузере без облачной задержки. Векторная биомеханика мгновенно измеряет сгибание суставов, наклон позвоночника и баланс плеч.",
        "sanmonBody": "Выполняйте приседания, жимы или выпады со звуковыми и визуальными индикаторами ошибок в реальном времени. Каждый кинематический градус на виду.",
        "sanmonCta": "Переступить порог (Запустить позу вживую)",
        "statModules": "Модулей", "statFps": "FPS Зрение", "statYoga": "Асан йоги", "statIntelligence": "Интеллект",
        "stillGardensApproach": "Подход", "stillGardensApproachMeta": "Адаптивные силовые сплиты • Автоповторения",
        "stillGardensApproachDesc": "5-фазный автомат состояний биомеханики, автоматические 60-секундные паузы и мышечные сплиты.",
        "stillGardensLanterns": "Фонари", "stillGardensLanternsMeta": "17 асан с таймером удержания",
        "stillGardensLanternsDesc": "Проверка осанки в реальном времени, подсветка целевых мышц и таймер контроля удержания позы.",
        "stillGardensMoonwater": "Лунная вода", "stillGardensMoonwaterMeta": "Метаболическая матрица • Анализатор питания",
        "stillGardensMoonwaterDesc": "Двойные клинические формулы BMR, TDEE, целевые пропорции БЖУ и анализ состава блюд через Gemini ИИ.",
        "sacredCraftHead": "Шесть дисциплин. Единый взаимосвязанный интеллект здоровья.",
        "sacredCraftSub": "Каждый модуль действует как независимая инженерная система, объединенная непрерывной биометрической телеметрией.",
        "craftVisionTitle": "Биомеханическое зрение", "craftVisionDesc": "33 сустава в реальном времени, телеметрия наклона позвоночника и сигнализация рисков.", "craftVisionBadge": "60 FPS",
        "craftStrengthTitle": "Адаптивная сила", "craftStrengthDesc": "Сплиты по группам мышц, автоматический счетчик повторений и таймер пауз.", "craftStrengthBadge": "{{count}} Сплитов",
        "craftYogaTitle": "Равновесие асан", "craftYogaDesc": "17 структурированных поз йоги с контролем углов суставов и удержания баланса.", "craftYogaBadge": "{{count}} Поз",
        "craftBmiTitle": "Метаболическая алхимия", "craftBmiDesc": "Точные формулы Mifflin-St Jeor и Harris-Benedict BMR, расчет TDEE и макросов.", "craftBmiBadge": "Клинический BMR",
        "craftFoodTitle": "Ежедневное питание", "craftFoodDesc": "Дневник приемов пищи, трекер воды и распознавание блюд через ИИ Gemini.", "craftFoodBadge": "ИИ Gemini",
        "craftOracleTitle": "Оракул", "craftOracleDesc": "Интерактивный коучинг Luna ИИ, рекомендации по восстановлению и индивидуальные программы.", "craftOracleBadge": "24/7 ИИ",
        "oracleHead": "Спросите Luna о тренировках, углах суставов или метаболизме.",
        "oracleSub": "Работая на базе нейросетей Gemini, Luna предоставляет персональные консультации, кинематический аудит и метаболические расчеты.",
        "oraclePrompt1Title": "Макросы для гипертрофии", "oraclePrompt1Desc": "Рассчитать белки, жиры и углеводы для прогрессивного роста мышечной массы.",
        "oraclePrompt2Title": "Кинематика приседаний", "oraclePrompt2Desc": "Биомеханические советы по углам сгибания коленей и положению спины.",
        "oraclePrompt3Title": "7-дневный план восстановления", "oraclePrompt3Desc": "Противовоспалительное меню для ускорения регенерации тканей и подвижности суставов.",
        "oracleCta": "ОТКРЫТЬ ДИАЛОГ С LUNA ИИ →",
        "afterlightEyebrow": "Глава 05 — Послесвечение // Клиническое досье",
        "afterlightTitle": "Послесвечение",
        "afterlightDesc": "Врата не закрываются за вами. Возьмите данные о здоровье с собой: экспортируйте отчеты в PDF, отправляйте досье на почту или создавайте видеообзоры в HD.",
        "afterlightCta": "Открыть студию экспорта",
        "faqEyebrow": "Глава 05.5 — Вопросы и ответы", "faqTag": "質疑 // КЛИНИЧЕСКИЕ И БИОМЕХАНИЧЕСКИЕ ВОПРОСЫ",
        "faqHead": "Биомеханическая точность и системная архитектура.",
        "faqSub": "Все о локальной конфиденциальности без облачных серверов, телеметрии 60 кадров/с и экспорте аналитики.",
        "faqQ1": "Как Luminix обеспечивает зрение 60 FPS без передачи видео на внешние серверы?",
        "faqA1": "Все нейросетевые вычисления MediaPipe происходят исключительно в вашем браузере через WASM и аппаратное ускорение WebGL. Ни единый пиксель не покидает устройство.",
        "faqQ2": "Какая камера требуется для отслеживания 33 точек тела?",
        "faqA2": "Подойдет любая стандартная веб-камера 720p или 1080p, встроенная камера ноутбука или смартфона.",
        "faqQ3": "Как система определяет завершенность повторения упражнения?",
        "faqA3": "Используется конечный автомат состояний (FSM), вычисляющий скалярные произведения векторов конечностей. Повторение засчитывается только при полной амплитуде.",
        "faqQ4": "Как рассчитывается базовый метаболизм (BMR) и суточная норма калорий?",
        "faqA4": "Применяются медицинские формулы Миффлина-Сент-Джеора и Харриса-Бенедикта, умноженные на коэффициент активности (PAL).",
        "faqQ5": "Насколько безопасны экспортируемые PDF-отчеты?",
        "faqA5": "Все досье соответствуют клиническим стандартам. Локальные данные шифруются, доступ защищен Argon2, JWT и встроенным веб-файрволом (WAF).",
        "creatorEyebrow": "Глава 06 — Архитектор", "creatorTag": "創造主 // СОЗДАТЕЛЬ И СИСТЕМА",
        "creatorHead": "Создано Рамом Чараном Теджей с бескомпромиссным видением.",
        "creatorSub": "В основе Luminix — стремление объединить сверхбыстрое компьютерное зрение на стороне клиента, клиническую биомеханику и кибер-эстетику Киото.",
        "creatorRole": "Full-Stack архитектор ИИ-систем, инженер компьютерного зрения. Единственный создатель экосистемы Luminix.",
        "creatorBio": "MediaPipe Vision • Архитектура FastAPI • WebGL и Three.js • Мультимодельный Gemini LLM • Кинематическая тригонометрия",
        "creatorViewDossier": "Открыть полное досье создателя и стек технологий", "creatorSupportSanctuary": "Поддержать создателя"
    },
    "gym": {
        "title": "Адаптивный силовой модуль", "pageTitle": "Силовой модуль // Умный счетчик повторений",
        "moduleTag": "МОДУЛЬ 02 // СИЛОВЫЕ ПРОТОКОЛЫ", "startWorkout": "Начать тренировку",
        "pauseWorkout": "Пауза", "resumeWorkout": "Возобновить", "endWorkout": "Завершить тренировку",
        "reps": "Повторения", "sets": "Подходы", "weight": "Вес (кг)", "restTimer": "Отдых",
        "exercise": "Упражнение", "targetMuscles": "Целевые мышцы", "formScore": "Оценка техники",
        "repState": "Фаза движения", "eccentric": "Эксцентрическая", "concentric": "Концентрическая", "lockout": "Фиксация",
        "depth": "Глубина", "repPace": "Темп", "nextExercise": "Следующее упражнение", "workoutSummary": "Итоги тренировки",
        "totalVolume": "Общий тоннаж", "completedSets": "Завершено подходов", "averageForm": "Средняя техника",
        "squat": "Приседания", "pushup": "Отжимания", "bicepCurl": "Сгибания на бицепс", "overheadPress": "Армейский жим", "lunge": "Выпады"
    },
    "luna": {
        "title": "Luna ИИ // Клинический ассистент", "pageTitle": "Luna ИИ — Диалог о биомеханике и метаболизме",
        "moduleTag": "МОДУЛЬ 06 // АВТОНОМНЫЙ ИНТЕЛЛЕКТ", "askLuna": "Спросите Luna...",
        "askPlaceholder": "Задайте вопрос об углах суставов, реабилитации или плане питания...",
        "send": "Отправить", "stop": "Стоп", "regenerate": "Сгенерировать заново", "clearChat": "Очистить чат",
        "newChat": "Новый диалог", "thinking": "Luna анализирует физиологические параметры...",
        "generating": "Формирование рекомендаций...", "suggestedQuestions": "Рекомендуемые вопросы",
        "copy": "Скопировать ответ", "copied": "Скопировано в буфер!", "error": "Ошибка связи с Luna ИИ",
        "retry": "Повторить попытку", "disclaimer": "Luna дает биомеханические советы, но не заменяет консультацию врача."
    },
    "notifications": {
        "title": "Уведомления", "markAllAsRead": "Отметить все как прочитанные", "noNotifications": "Нет новых уведомлений",
        "savedSuccessfully": "Успешно сохранено", "workoutCompleted": "Тренировка завершена",
        "deviceConnected": "Биометрический датчик подключен", "profileUpdated": "Профиль успешно обновлен",
        "languageChanged": "Язык успешно изменен", "analysisCompleted": "Биомеханический анализ завершен",
        "connectionFailed": "Сбой подключения", "formWarning": "Внимание: отклонение техники от нормы",
        "repCounted": "Повторение зафиксировано", "restFinished": "Отдых окончен — Готовы к подходу",
        "pdfGenerated": "Клинический отчет PDF успешно создан"
    },
    "nutrition": {
        "title": "Метаболическая матрица и питание", "pageTitle": "Метаболическая матрица — BMR и TDEE",
        "moduleTag": "МОДУЛЬ 04 // МЕТАБОЛИЧЕСКИЙ ИНТЕЛЛЕКТ", "bmr": "Базовый метаболизм (BMR)",
        "tdee": "Суточный расход энергии (TDEE)", "calories": "Калории", "protein": "Белки",
        "carbs": "Углеводы", "fats": "Жиры", "waterTracker": "Трекер воды", "addWater": "Добавить воду (250 мл)",
        "targetWater": "Цель по воде", "mealLog": "Дневник питания", "logMeal": "Записать прием пищи",
        "foodAnalysis": "ИИ-анализ блюд", "scanFood": "Опишите или сфотографируйте еду...",
        "dietaryGoal": "Цель по питанию", "hypertrophy": "Набор мышечной массы",
        "cutting": "Снижение жировой массы", "maintenance": "Поддержание веса", "macroBreakdown": "Баланс макронутриентов"
    },
    "pose": {
        "title": "Движок позы 60 кадров/с", "pageTitle": "Живая поза (60 FPS) — Биомеханика кинематики",
        "moduleTag": "МОДУЛЬ 01 // БИОМЕХАНИЧЕСКАЯ КИНЕМАТИКА", "poseAnalysis": "Анализ позы",
        "startAnalysis": "Начать анализ", "stopAnalysis": "Остановить анализ", "cameraPermissions": "Требуется доступ к камере",
        "cameraInstructions": "Разрешите доступ к веб-камере для отслеживания движений со скоростью 60 FPS.",
        "grantAccess": "Предоставить доступ", "bodyTracking": "Трекинг тела", "poseDetection": "Распознавание позы",
        "jointTracking": "Трекинг суставов", "movementTracking": "Трекинг движений", "posture": "Осанка",
        "form": "Техника", "alignment": "Выравнивание", "riskDetection": "Определение риска", "riskLevel": "Уровень риска",
        "movementQuality": "Качество движения", "recommendations": "Рекомендации", "warnings": "Предупреждения",
        "exerciseFeedback": "Обратная связь в реальном времени", "analysisResults": "Результаты анализа", "confidence": "Точность модели",
        "highRisk": "Высокий риск травмы — исправьте технику", "mediumRisk": "Средний риск — скорректируйте углы",
        "lowRisk": "Оптимальная биомеханическая форма", "safeForm": "Безопасная техника", "jointAngles": "Углы суставов",
        "toggleAngles": "Показать углы", "toggleMirror": "Отразить изображение камеры", "sessionDuration": "Длительность",
        "alertCount": "Предупреждения", "fps": "Кадров в секунду (FPS)", "processing": "Обработка..."
    },
    "settings": {
        "title": "Настройки системы", "profile": "Биометрический профиль", "account": "Управление аккаунтом",
        "language": "Язык / Language", "appearance": "Внешний вид", "theme": "Цветовая тема",
        "darkMode": "Темная тема Святилища", "lightMode": "Светлая тема", "notifications": "Уведомления и сигналы",
        "privacy": "Суверенная конфиденциальность", "security": "Безопасность и ключи", "connectedDevices": "Датчики",
        "healthDevices": "Фитнес-трекеры", "data": "Экспорт данных", "aiSettings": "Параметры ИИ",
        "logout": "Выйти", "deleteAccount": "Удалить аккаунт навсегда",
        "deleteAccountConfirm": "Вы уверены, что хотите удалить аккаунт и все сохраненные биометрические данные?",
        "saveChanges": "Сохранить изменения", "changesSaved": "Настройки успешно сохранены.",
        "fullName": "Полное имя", "age": "Возраст", "bodyWeight": "Вес (кг)", "heightCm": "Рост (см)",
        "gender": "Пол", "selectGender": "Выберите пол", "primaryGoal": "Основная цель",
        "hypertrophy": "Гипертрофия мышц", "fatLoss": "Сжигание жира", "biomechanics": "Осанка и подвижность",
        "endurance": "Выносливость", "customProfilePicture": "Фото профиля",
        "storedSecurely": "Надежно зашифровано в локальном хранилище браузера", "selectAvatarImage": "Выбрать изображение",
        "saveInitialize": "Сохранить и инициализировать", "personalizeSanctuary": "Персонализация святилища",
        "sanctuaryWord": "Святилище", "biometricRegistry": "Биометрический реестр",
        "biometricDescription": "Физиологические параметры калибруют алгоритмы компьютерного зрения и метаболические формулы."
    },
    "yoga": {
        "title": "17 священных асан йоги", "pageTitle": "Йога // Палата телесного равновесия",
        "moduleTag": "МОДУЛЬ 03 // РАВНОВЕСИЕ", "pose": "Асана", "breathing": "Дыхание",
        "duration": "Длительность", "difficulty": "Сложность", "instructions": "Инструкция по выравниванию",
        "startSession": "Начать занятие", "endSession": "Завершить занятие", "beginner": "Начальный",
        "intermediate": "Средний", "advanced": "Продвинутый", "safetyWarnings": "Безопасность суставов",
        "recommendations": "Советы по балансу", "progress": "Прогресс", "holdTime": "Время удержания",
        "holdDuration": "Целевое удержание", "poseGuide": "Руководство по асане", "alignmentTips": "Точки контроля",
        "benefits": "Физиологическая польза", "asanaLibrary": "Библиотека асан", "selectedPose": "Выбранная асана",
        "formAccuracy": "Точность позы", "breathingPattern": "Ритм дыхания",
        "inhale": "Вдох", "exhale": "Выдох", "hold": "Задержка", "relax": "Расслабление"
    }
}

# Write fr.py and ru.py
with open(LOCALES_DATA_DIR / "fr.py", "w", encoding="utf-8") as f:
    f.write('"""French (fr) translation module for Luminix."""\n\nFR_TRANSLATIONS = ' + repr(FR_TRANSLATIONS) + '\n')
print(f"Generated fr.py with {sum(len(v) for v in FR_TRANSLATIONS.values())} keys")

with open(LOCALES_DATA_DIR / "ru.py", "w", encoding="utf-8") as f:
    f.write('"""Russian (ru) translation module for Luminix."""\n\nRU_TRANSLATIONS = ' + repr(RU_TRANSLATIONS) + '\n')
print(f"Generated ru.py with {sum(len(v) for v in RU_TRANSLATIONS.values())} keys")
